//! IPC surface: every command and event the webview can use.
//!
//! Types are exported to `apps/desktop/src/lib/ipc/bindings.ts` by tauri-specta.
//! Never edit that file by hand; run `pnpm bindings`.

// Tauri extracts command arguments (e.g. `AppHandle`) by value.
#![allow(clippy::needless_pass_by_value)]

mod app;
mod events;

use std::path::PathBuf;

use specta_typescript::Typescript;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands, collect_events};

use events::EntityChanged;

const BINDINGS_HEADER: &str = "// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.\n// Regenerate with `pnpm bindings`.\n";

/// The specta builder holding every command and event.
pub(crate) fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![app::app_info, app::app_ready])
        .events(collect_events![EntityChanged])
}

/// Path of the generated TypeScript bindings.
fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc/bindings.ts")
}

/// Writes the TypeScript bindings and returns the path written.
///
/// # Errors
/// Returns an error if the types can't be exported or the file can't be written.
pub fn export_bindings() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = bindings_path();
    builder().export(Typescript::default().header(BINDINGS_HEADER), &path)?;
    Ok(path)
}
