//! IPC surface: every command and event the webview can use.
//!
//! Types are exported to `apps/desktop/src/lib/ipc/bindings.ts` by tauri-specta.
//! Never edit that file by hand; run `pnpm bindings`.

// Tauri extracts command arguments (e.g. `AppHandle`) by value.
#![allow(clippy::needless_pass_by_value)]

mod accounts;
mod analytics;
pub(crate) mod app;
pub(crate) mod cli;
pub(crate) use app::mark_launch;
mod doctor;
mod domain_shares;
mod events;
mod quick_share;
mod routes;
pub(crate) use routes::{start_machine, stop_machine};
mod settings;
mod updates;

use std::path::PathBuf;

use specta_typescript::Typescript;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands, collect_events};

pub use events::{EntityChanged, EntityKind, MenuAction, MenuCommand};

const BINDINGS_HEADER: &str = "// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.\n// Regenerate with `pnpm bindings`.\n";

/// The specta builder holding every command and event.
pub(crate) fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            app::app_info,
            updates::updates_status,
            cli::cli_status,
            cli::cli_install,
            cli::cli_uninstall,
            updates::updates_check,
            updates::updates_restart,
            app::app_save_log,
            app::app_ready,
            app::app_accent_color,
            app::app_report_error,
            app::app_open_settings,
            app::app_request_quit,
            app::app_open_help,
            app::app_quit,
            app::app_open_at_login,
            app::app_set_open_at_login,
            settings::settings_get,
            settings::settings_set,
            domain_shares::domain_shares_list,
            domain_shares::domain_shares_start,
            domain_shares::domain_shares_stop,
            quick_share::quick_share_cli_list,
            quick_share::quick_share_cli_stop,
            quick_share::binary_status,
            quick_share::binary_install,
            quick_share::binary_check_update,
            quick_share::binary_reveal,
            quick_share::services_list,
            quick_share::quick_share_start,
            quick_share::quick_share_set_host_header,
            quick_share::quick_share_check,
            quick_share::quick_share_stop,
            quick_share::quick_share_list,
            quick_share::quick_share_stats,
            quick_share::quick_share_logs,
            quick_share::quick_share_qr,
            accounts::accounts_list,
            accounts::accounts_add_token,
            accounts::accounts_open_token_page,
            accounts::accounts_detect_cert,
            accounts::accounts_import_cert,
            accounts::accounts_remove,
            accounts::accounts_capabilities,
            accounts::domains_list,
            accounts::accounts_oauth_available,
            accounts::accounts_oauth_sign_in,
            accounts::accounts_oauth_cancel,
            routes::routes_overview,
            routes::routes_preview,
            routes::routes_apply,
            routes::routes_verify,
            routes::routes_drift,
            routes::routes_balance_health,
            routes::routes_keep_theirs,
            routes::routes_activity,
            routes::tunnels_list,
            routes::tunnels_start,
            routes::tunnels_stop,
            routes::tunnels_clean,
            routes::import_scan,
            routes::foreign_list,
            routes::foreign_stop,
            routes::tunnels_logs,
            routes::tunnels_remote_logs,
            routes::tunnels_remote_logs_stop,
            routes::routes_logs,
            routes::routes_export,
            routes::routes_export_save,
            routes::tunnels_traffic,
            routes::tunnels_traffic_history,
            routes::tunnels_always_on,
            routes::tunnels_set_always_on,
            routes::tunnels_adopt,
            doctor::doctor_run,
            doctor::doctor_set_ignored,
            doctor::doctor_fix_safe,
            doctor::diagnostics_preview,
            doctor::diagnostics_export,
            analytics::analytics_summary,
            analytics::analytics_route,
            analytics::uptime_list,
            analytics::uptime_route,
            analytics::alerts_get,
            analytics::alerts_set
        ])
        .events(collect_events![EntityChanged, MenuAction])
}

/// Path of the generated TypeScript bindings.
fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc/bindings.ts")
}

/// Writes the TypeScript bindings and returns the path written.
///
/// # Errors
/// Returns an error if the types can't be exported or the file can't be written.
pub fn export_bindings() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = bindings_path();
    builder().export(Typescript::default().header(BINDINGS_HEADER), &path)?;
    Ok(path)
}
