//! IPC surface: every command and event the webview can use.
//!
//! Types are exported to `apps/desktop/src/lib/ipc/bindings.ts` by tauri-specta.
//! Never edit that file by hand; run `pnpm bindings`.

// Tauri extracts command arguments (e.g. `AppHandle`) by value.
#![allow(clippy::needless_pass_by_value)]

mod accounts;
mod ai_clients;
mod analytics;
pub(crate) mod app;
mod backup;
pub(crate) mod cli;
pub(crate) mod comments;
pub(crate) use app::mark_launch;
mod doctor;
mod domain_shares;
mod events;
mod exposure;
mod fronts;
mod inspect;
mod integrations;
mod local_domains;
mod projects;
mod quick_share;
mod reservations;
mod routes;
pub(crate) use routes::{start_machine, stop_machine};
mod protection;
mod settings;
mod sharing;
mod snapshots;
mod updates;

use std::path::PathBuf;

use specta_typescript::Typescript;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands, collect_events};

pub use events::{EntityChanged, EntityKind, MenuAction, MenuCommand, OpenView, ViewTarget};

const BINDINGS_HEADER: &str = "// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.\n// Regenerate with `pnpm bindings`.\n";

/// The specta builder holding every command and event.
/// Runs blocking work (files, processes, system calls) on a blocking thread. On macOS
/// synchronous commands run on the main thread, where a slow disk or system call freezes
/// every window, so commands that do such work are async and call this.
pub(crate) async fn off_main<T: Send + 'static>(
    work: impl FnOnce() -> T + Send + 'static,
) -> Result<T, crate::error::AppError> {
    tauri::async_runtime::spawn_blocking(work)
        .await
        .map_err(
            |_| crate::error::AppError::internal(teitunnel_core::text::msg::app::interrupted()),
        )
}

pub(crate) fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            app::app_info,
            updates::updates_status,
            cli::cli_status,
            cli::cli_install,
            cli::cli_uninstall,
            ai_clients::ai_clients_status,
            ai_clients::ai_agents,
            ai_clients::ai_clients_connect,
            ai_clients::ai_clients_disconnect,
            updates::updates_check,
            updates::updates_restart,
            app::app_save_log,
            app::app_ready,
            app::app_accent_color,
            app::app_report_error,
            app::app_open_settings,
            app::app_request_quit,
            app::app_open_help,
            app::app_quit,
            app::app_open_at_login,
            app::app_set_open_at_login,
            settings::settings_get,
            settings::settings_set,
            domain_shares::domain_shares_list,
            domain_shares::domain_shares_start,
            domain_shares::domain_shares_stop,
            sharing::sharing_set_paused,
            sharing::sharing_schedules,
            sharing::sharing_set_schedule,
            sharing::sharing_name_suggestions,
            sharing::sharing_expand_name,
            sharing::sharing_folder,
            sharing::sharing_choose_folder,
            sharing::sharing_start_folder_on_domain,
            quick_share::quick_share_cli_list,
            quick_share::quick_share_cli_stop,
            quick_share::binary_status,
            quick_share::binary_install,
            quick_share::binary_check_update,
            quick_share::binary_reveal,
            quick_share::services_list,
            quick_share::quick_share_start,
            quick_share::quick_share_start_folder,
            quick_share::quick_share_set_host_header,
            quick_share::quick_share_check,
            quick_share::quick_share_stop,
            quick_share::quick_share_list,
            quick_share::quick_share_stats,
            quick_share::quick_share_logs,
            quick_share::quick_share_qr,
            accounts::accounts_list,
            accounts::accounts_add_token,
            accounts::accounts_open_token_page,
            accounts::accounts_detect_cert,
            accounts::accounts_import_cert,
            accounts::accounts_remove,
            accounts::accounts_capabilities,
            accounts::domains_list,
            accounts::accounts_oauth_available,
            accounts::accounts_oauth_sign_in,
            accounts::accounts_oauth_cancel,
            routes::routes_overview,
            routes::routes_preview,
            routes::routes_apply,
            routes::routes_verify,
            routes::routes_drift,
            routes::routes_balance_health,
            routes::routes_keep_theirs,
            routes::routes_activity,
            routes::tunnels_list,
            routes::tunnels_start,
            routes::tunnels_stop,
            routes::tunnels_clean,
            routes::import_scan,
            routes::foreign_list,
            routes::foreign_stop,
            routes::tunnels_logs,
            routes::tunnels_remote_logs,
            routes::tunnels_remote_logs_stop,
            routes::routes_logs,
            routes::routes_export,
            routes::routes_export_save,
            routes::tunnels_traffic,
            routes::tunnels_traffic_history,
            routes::tunnels_always_on,
            routes::tunnels_set_always_on,
            routes::tunnels_adopt,
            doctor::doctor_run,
            doctor::doctor_set_ignored,
            doctor::doctor_fix_safe,
            doctor::diagnostics_preview,
            doctor::diagnostics_export,
            analytics::analytics_summary,
            analytics::analytics_route,
            analytics::uptime_list,
            analytics::uptime_route,
            analytics::alerts_get,
            analytics::alerts_set,
            snapshots::snapshots_list,
            snapshots::snapshots_versions,
            snapshots::snapshots_choose_folder,
            snapshots::snapshots_detect_project,
            snapshots::snapshots_prepare_folder,
            snapshots::snapshots_prepare_build,
            snapshots::snapshots_prepare_crawl,
            snapshots::snapshots_preview,
            snapshots::snapshots_apply,
            integrations::integrations_get,
            integrations::integrations_set,
            integrations::integrations_revoke,
            reservations::reservations_list,
            reservations::reservations_availability,
            protection::protection_get,
            protection::protection_tokens,
            protection::protection_preview,
            protection::protection_apply,
            protection::protection_copy_secret,
            protection::protection_forget_secret,
            projects::projects_list,
            projects::projects_choose_folder,
            projects::projects_add,
            projects::projects_remove,
            projects::projects_modified,
            projects::projects_status,
            projects::projects_apply,
            exposure::exposure_check,
            backup::backup_choose_save,
            backup::backup_choose_open,
            backup::backup_create,
            backup::backup_inspect,
            backup::backup_restore,
            inspect::inspect_settings_get,
            inspect::inspect_settings_set,
            inspect::inspect_taps,
            inspect::inspect_known_taps,
            inspect::inspect_exchanges,
            inspect::inspect_exchange,
            inspect::inspect_subscribe,
            inspect::inspect_unsubscribe,
            inspect::inspect_replay,
            inspect::inspect_export,
            inspect::inspect_export_save,
            inspect::inspect_openapi_save,
            inspect::inspect_clear,
            inspect::inspect_configure,
            inspect::inspect_protect,
            inspect::inspect_metrics,
            inspect::inspect_webhook_secrets,
            inspect::inspect_webhook_secret_set,
            inspect::inspect_webhook_secret_remove,
            inspect::inspect_webhook_verify,
            inspect::inspect_routes,
            inspect::inspect_route_preview,
            inspect::inspect_route_apply,
            quick_share::quick_share_set_inspected,
            quick_share::quick_share_set_paused,
            local_domains::local_domains_status,
            local_domains::local_domains_add,
            local_domains::local_domains_update,
            local_domains::local_domains_set_inspect,
            local_domains::local_domains_remove,
            local_domains::local_domains_set_lan,
            local_domains::local_domains_restart,
            local_domains::local_domains_trust_status,
            local_domains::local_domains_trust,
            local_domains::local_domains_untrust,
            local_domains::local_domains_run_as_admin,
            local_domains::local_domains_fix,
            local_domains::local_domains_save_ca,
            comments::comments_subjects,
            comments::comments_threads,
            comments::comments_reply,
            comments::comments_resolve,
            comments::comments_forget,
            comments::comments_set_tap,
            fronts::fronts_list,
            fronts::fronts_preview,
            fronts::fronts_undo_change,
            fronts::fronts_apply,
            fronts::fronts_inbox_secrets,
            fronts::fronts_inbox_secret_set,
            fronts::inbox_items,
            fronts::inbox_deliver
        ])
        .events(collect_events![EntityChanged, MenuAction, OpenView])
}

/// Path of the generated TypeScript bindings.
fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc/bindings.ts")
}

/// Writes the TypeScript bindings and returns the path written.
///
/// # Errors
/// Returns an error if the types can't be exported or the file can't be written.
pub fn export_bindings() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = bindings_path();
    builder().export(Typescript::default().header(BINDINGS_HEADER), &path)?;
    Ok(path)
}
