// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Regenerate with `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app version, platform and data directory. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Called by a webview once its first frame is painted; shows its window. */
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	/**  The system accent colour as `#rrggbb`, or `null` to keep the stylesheet default. */
	appAccentColor: () => __TAURI_INVOKE<string | null>("app_accent_color"),
	/**  Records an uncaught webview error in the app log (redacted like every other line). */
	appReportError: (message: string, stack: string | null) => __TAURI_INVOKE<void>("app_report_error", { message, stack }),
	/**  Opens the Settings window (same as ⌘,). */
	appOpenSettings: () => __TAURI_INVOKE<null>("app_open_settings"),
	/**  Returns all settings, with defaults applied. */
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	/**  Updates the given settings and returns the result. Every window is notified. */
	settingsSet: (patch: SettingsPatch) => __TAURI_INVOKE<Settings>("settings_set", { patch }),
	/**  The cloudflared binary in use, or `null` if none is installed. */
	binaryStatus: () => __TAURI_INVOKE<{
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
} | null>("binary_status"),
	/**  Downloads, verifies and installs the latest cloudflared into the app data folder. */
	binaryInstall: (onProgress: Channel<InstallProgress>) => __TAURI_INVOKE<BinaryInfo>("binary_install", { onProgress }),
	/**  Checks Cloudflare's releases for a newer cloudflared. */
	binaryCheckUpdate: () => __TAURI_INVOKE<UpdateInfo>("binary_check_update"),
	/**  Shows the binary in Finder. */
	binaryReveal: () => __TAURI_INVOKE<null>("binary_reveal"),
	/**  Services listening on this Mac, likely dev servers first. */
	servicesList: () => __TAURI_INVOKE<LocalService[]>("services_list"),
	/**  Starts sharing `origin`. The URL arrives via `EntityChanged` for `quickShares`. */
	quickShareStart: (origin: string, stopAfterMinutes: number | null) => __TAURI_INVOKE<QuickShare>("quick_share_start", { origin, stopAfterMinutes }),
	/**  Stops a share. */
	quickShareStop: (id: string) => __TAURI_INVOKE<null>("quick_share_stop", { id }),
	/**  Running shares, newest first. */
	quickShareList: () => __TAURI_INVOKE<QuickShare[]>("quick_share_list"),
	/**  Request counts for a share (polled by the UI while visible). */
	quickShareStats: (id: string) => __TAURI_INVOKE<ShareStats>("quick_share_stats", { id }),
	/**  The newest cloudflared log lines of a share. */
	quickShareLogs: (id: string, limit: number) => __TAURI_INVOKE<LogLine[]>("quick_share_logs", { id, limit }),
	/**  An SVG QR code for `url` (dark modules use `currentColor`). */
	quickShareQr: (url: string) => __TAURI_INVOKE<string>("quick_share_qr", { url }),
	/**  Connected accounts. */
	accountsList: () => __TAURI_INVOKE<Account[]>("accounts_list"),
	/**
	 *  Verifies an API token and connects every account it reaches. The token is stored in
	 *  the keychain and never sent back.
	 */
	accountsAddToken: (token: string) => __TAURI_INVOKE<Account[]>("accounts_add_token", { token }),
	/**  Opens Cloudflare's "Create API token" page with Teitunnel's permissions pre-selected. */
	accountsOpenTokenPage: () => __TAURI_INVOKE<null>("accounts_open_token_page"),
	/**  Whether `~/.cloudflared/cert.pem` (from `cloudflared tunnel login`) exists. */
	accountsDetectCert: () => __TAURI_INVOKE<boolean>("accounts_detect_cert"),
	/**  Imports the login from `~/.cloudflared/cert.pem` (the file is only read). */
	accountsImportCert: () => __TAURI_INVOKE<Account>("accounts_import_cert"),
	/**  Disconnects an account and deletes its credentials from the keychain. */
	accountsRemove: (id: string) => __TAURI_INVOKE<null>("accounts_remove", { id }),
	/**  What the account's credential can do. */
	accountsCapabilities: (id: string) => __TAURI_INVOKE<Capabilities>("accounts_capabilities", { id }),
	/**  Domains in an account. */
	domainsList: (accountId: string) => __TAURI_INVOKE<Domain[]>("domains_list", { accountId }),
};

/** Events */
export const events = {
	entityChanged: makeEvent<EntityChanged>("entity-changed"),
	menuAction: makeEvent<MenuAction>("menu-action"),
};

/* Types */
/**  A connected Cloudflare account. */
export type Account = {
	/**  Cloudflare account id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  How it was connected. */
	credential: CredentialKind,
	/**  For cert.pem credentials: the only zone the credential works for. */
	limitedZone: string | null,
};

/**  An error as shown to the user: what happened, and what to do about it. */
export type AppError = {
	/**  Category for programmatic handling. */
	code: ErrorCode,
	/**  One sentence describing what happened. */
	message: string,
	/**  What the user can do about it. */
	hint: string | null,
	/**  The input field the error refers to. */
	field: string | null,
};

/**  Static facts about the running app. */
export type AppInfo = {
	/**  App version (semver). */
	version: string,
	/**  Operating system: `macos`, `linux` or `windows`. */
	platform: string,
	/**  CPU architecture, e.g. `aarch64`. */
	arch: string,
	/**  Directory holding the database, logs and managed binaries. */
	dataDir: string,
};

/**  Where cloudflared comes from and whether it's new enough. */
export type BinaryInfo = {
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
};

/**  Everything a credential can do in one account. */
export type Capabilities = {
	/**  List domains. */
	zonesRead: Grant,
	/**  List tunnels. */
	tunnelsRead: Grant,
	/**  Create and configure tunnels. */
	tunnelsEdit: Grant,
	/**  Access policies (optional feature). */
	accessEdit: Grant,
	/**  DNS editing, per domain. */
	zones: ZoneGrant[],
};

/**  How an account was connected. */
export type CredentialKind = 
/**  A user API token. */
"apiToken" | 
/**  OAuth sign-in (refresh token in the keychain). */
"oAuth" | 
/**  Imported from `cloudflared tunnel login` (cert.pem); one zone only. */
"certPem";

/**  A domain in a connected account. */
export type Domain = {
	/**  Zone id. */
	id: string,
	/**  Domain name. */
	name: string,
	/**  Setup state. */
	status: DomainStatus,
	/**  Cloudflare nameservers to set at the registrar. */
	nameServers: string[],
	/**  Nameservers currently at the registrar (before the switch). */
	originalNameServers: string[],
	/**  Plan name. */
	plan: string | null,
	/**  Whether the proxy is paused. */
	paused: boolean,
};

/**  Where a domain is in its setup. */
export type DomainStatus = 
/**  Active on Cloudflare: routes can use it. */
"active" | 
/**  Waiting for the registrar to switch nameservers. */
"pending" | 
/**  Nameservers moved away from Cloudflare. */
"moved" | 
/**  Being set up, or a state we don't know. */
"other";

/**  Emitted after anything changes, so the UI can invalidate the affected queries. */
export type EntityChanged = {
	/**  What kind of entity changed. */
	kind: EntityKind,
	/**  Which one, when a single entity changed. */
	id: string | null,
};

/**  Kinds of entities the UI caches. Each maps to TanStack Query keys on the frontend. */
export type EntityKind = 
/**  App settings. */
"settings" | 
/**  Quick Shares (list, status, URL). */
"quickShares" | 
/**  Connected Cloudflare accounts (and their domains). */
"accounts";

/**  Machine-readable error category. The frontend branches on this, never on `message`. */
export type ErrorCode = 
/**  An unexpected failure. The message is safe to show; details are in the app log. */
"internal" | 
/**  The input was rejected; `field` names the offending field. */
"invalidInput" | 
/**  The thing acted on doesn't exist (any more). */
"notFound" | 
/**  cloudflared isn't installed. */
"cloudflaredMissing" | 
/**  Busy or exhausted; retrying later may work. */
"unavailable";

/**  The result of probing one permission. */
export type Grant = 
/**  Allowed. */
"yes" | 
/**  Not allowed. */
"no" | 
/**  Couldn't be checked right now. */
"unknown";

/**  Install progress, streamed to the webview. */
export type InstallProgress = 
/**  Downloading: bytes received of total. */
{ step: "downloading"; 
/**  Bytes received. */
received: number; 
/**  Total bytes. */
total: number } | 
/**  Checking checksums and the code signature. */
{ step: "verifying" } | 
/**  Moving the binary into place. */
{ step: "installing" };

/**  A TCP port something on this machine is listening on. */
export type LocalService = {
	/**  The port. */
	port: number,
	/**  Whether it listens on all interfaces (vs. loopback only). */
	allInterfaces: boolean,
	/**  Owning process id. */
	pid: number,
	/**  Process name, e.g. `node`. */
	process: string,
	/**  What it looks like, e.g. a Vite dev server. */
	kind: ServiceKind,
	/**  Project the process runs in (from its working directory), e.g. `my-app`. */
	project: string | null,
	/**  Suggested origin URL, e.g. `http://localhost:5173`. */
	origin: string,
};

/**  One cloudflared log line, for the log drawer. */
export type LogLine = {
	/**  Timestamp as printed by cloudflared. */
	time: string | null,
	/**  `debug`, `info`, `warn`, `error`, `fatal` or `raw`. */
	level: string,
	/**  The message. */
	message: string,
	/**  The `error` field, if any. */
	error: string | null,
};

/**  Emitted when a menu-bar item that the webview handles is chosen. */
export type MenuAction = {
	/**  The chosen command. */
	command: MenuCommand,
};

/**  A menu-bar command the webview handles (navigation, panes, palette). */
export type MenuCommand = 
/**  File ▸ New Route (⌘N). */
"newRoute" | 
/**  File ▸ New Quick Share (⇧⌘N). */
"newQuickShare" | 
/**  View ▸ Toggle Sidebar (⌥⌘S). */
"toggleSidebar" | 
/**  View ▸ Toggle Inspector (⌥⌘I). */
"toggleInspector" | 
/**  View ▸ Refresh (⌘R). */
"refresh" | 
/**  View ▸ Command Palette (⌘K). */
"commandPalette" | 
/**  View ▸ Overview (⌘1). */
"goOverview" | 
/**  View ▸ Routes (⌘2). */
"goRoutes" | 
/**  View ▸ Quick Share (⌘3). */
"goQuickShare" | 
/**  View ▸ Domains (⌘4). */
"goDomains" | 
/**  View ▸ Tunnels (⌘5). */
"goTunnels" | 
/**  View ▸ Activity (⌘6). */
"goActivity" | 
/**  View ▸ Doctor (⌘7). */
"goDoctor";

/**
 *  An HTTP(S) origin cloudflared can proxy to, e.g. `http://localhost:3000`.
 * 
 *  Parsing is forgiving about what people type: `3000`, `:3000`, `localhost:3000`,
 *  `127.0.0.1:8080` and full URLs all work. Paths and query strings are dropped;
 *  cloudflared proxies the whole host.
 */
export type OriginUrl = string;

/**  A running Quick Share, as the UI sees it. */
export type QuickShare = {
	/**  Identifier. */
	id: string,
	/**  The local service being shared. */
	origin: OriginUrl,
	/**  The public URL, once cloudflared has one. */
	url: string | null,
	/**  Current status. */
	status: ShareStatus,
	/**
	 *  Start time, milliseconds since the Unix epoch.
	 * 
	 *  Exported to TypeScript as `number` (values stay far below 2^53). The `u32` is
	 *  only a type hint for specta, which exports `u64` as bigint and `f64` as nullable.
	 */
	startedAt: number,
	/**  When it stops by itself, milliseconds since the Unix epoch. */
	stopAt: number | null,
};

/**  What a listening process appears to be. */
export type ServiceKind = 
/**  Vite dev server. */
"vite" | 
/**  Next.js. */
"next" | 
/**  Astro. */
"astro" | 
/**  Nuxt. */
"nuxt" | 
/**  Another Node.js / Bun / Deno server. */
"node" | 
/**  Python (Django, Flask, FastAPI/uvicorn, http.server…). */
"python" | 
/**  Ruby (Rails, Puma…). */
"ruby" | 
/**  PHP. */
"php" | 
/**  Java / JVM. */
"java" | 
/**  Go. */
"go" | 
/**  A port published by Docker, OrbStack or Colima. */
"docker" | 
/**  A database or cache (not HTTP). */
"database" | 
/**  A macOS system service, e.g. AirPlay Receiver on 5000/7000. */
"system" | 
/**  Anything else. */
"other";

/**  All preferences, with defaults applied. */
export type Settings = {
	/**  Appearance override. */
	theme: Theme,
	/**  Show the Teitunnel icon in the menu bar. */
	showInMenuBar: boolean,
};

/**  A partial update: only the fields that are set change. */
export type SettingsPatch = {
	/**  New appearance override. */
	theme?: Theme | null,
	/**  New menu bar visibility. */
	showInMenuBar?: boolean | null,
};

/**  Live traffic numbers for a share. */
export type ShareStats = {
	/**  Requests served. */
	requests: number,
	/**  Requests that failed. */
	errors: number,
};

/**  Where a share is in its life. */
export type ShareStatus = 
/**  cloudflared is starting and asking for a URL. */
{ status: "starting" } | 
/**  The URL works. */
{ status: "live" } | 
/**  Connection lost; cloudflared is reconnecting or restarting. */
{ status: "reconnecting" } | 
/**  It failed and won't recover by itself. */
{ status: "failed"; 
/**  What went wrong, for the user. */
message: string };

/**  Appearance override. */
export type Theme = 
/**  Follow the system appearance. */
"system" | 
/**  Always light. */
"light" | 
/**  Always dark. */
"dark";

/**  Whether a newer cloudflared is available. */
export type UpdateInfo = {
	/**  Latest published version. */
	latest: string,
	/**  Whether it's newer than the one in use (or none is installed). */
	available: boolean,
};

/**  DNS permission for one domain. */
export type ZoneGrant = {
	/**  Zone id. */
	zoneId: string,
	/**  Domain name. */
	zoneName: string,
	/**  Whether DNS records can be edited. */
	dnsEdit: Grant,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

