// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Regenerate with `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app version, platform and data directory. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Where updates stand. */
	updatesStatus: () => __TAURI_INVOKE<UpdateStatus>("updates_status"),
	/**  Whether the command line tool is on the PATH, and how to put it there. */
	cliStatus: () => __TAURI_INVOKE<CliState>("cli_status"),
	/**  Puts the command line tool on the PATH. */
	cliInstall: () => __TAURI_INVOKE<CliState>("cli_install"),
	/**  Removes the command line tool Teitunnel installed. */
	cliUninstall: () => __TAURI_INVOKE<CliState>("cli_uninstall"),
	/**  Checks for an update now (and downloads it), even with automatic checks off. */
	updatesCheck: () => __TAURI_INVOKE<UpdateStatus>("updates_check"),
	/**  Quits, installs the downloaded update and starts the new version. */
	updatesRestart: () => __TAURI_INVOKE<void>("updates_restart"),
	/**
	 *  Saves log lines (as shown, after filtering) to a text file in Downloads, with
	 *  anything secret-looking redacted, and shows it in Finder. Returns its path.
	 */
	appSaveLog: (lines: string[]) => __TAURI_INVOKE<string>("app_save_log", { lines }),
	/**
	 *  Called by a webview once its first frame is painted; shows its window. The first
	 *  call logs how long startup took (a diagnostic, and what `pnpm perf:app` reads).
	 */
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	/**  The system accent colour as `#rrggbb`, or `null` to keep the stylesheet default. */
	appAccentColor: () => __TAURI_INVOKE<string | null>("app_accent_color"),
	/**  Records an uncaught webview error in the app log (redacted like every other line). */
	appReportError: (message: string, stack: string | null) => __TAURI_INVOKE<void>("app_report_error", { message, stack }),
	/**  Opens the Settings window (same as ⌘,). */
	appOpenSettings: () => __TAURI_INVOKE<null>("app_open_settings"),
	/**
	 *  Quits like ⌘Q: asks first when routes run on the app's connectors (Windows and
	 *  Linux have no app menu to quit from).
	 */
	appRequestQuit: () => __TAURI_INVOKE<void>("app_request_quit"),
	/**  Opens a help page in the browser (the Help menu on macOS, the palette everywhere). */
	appOpenHelp: (link: HelpLink) => __TAURI_INVOKE<null>("app_open_help", { link }),
	/**
	 *  Quits after the user confirmed. With `keep_running`, this Mac's connectors switch to
	 *  Always-on first (so routes stay up); if that fails, the app stays open.
	 */
	appQuit: (keepRunning: boolean) => __TAURI_INVOKE<null>("app_quit", { keepRunning }),
	/**  Whether Teitunnel opens at login (hidden, in the menu bar). */
	appOpenAtLogin: () => __TAURI_INVOKE<boolean>("app_open_at_login"),
	/**  Turns opening at login on or off. */
	appSetOpenAtLogin: (enabled: boolean) => __TAURI_INVOKE<null>("app_set_open_at_login", { enabled }),
	/**  Returns all settings, with defaults applied. */
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	/**  Updates the given settings and returns the result. Every window is notified. */
	settingsSet: (patch: SettingsPatch) => __TAURI_INVOKE<Settings>("settings_set", { patch }),
	/**  Shares on your domains, in every account, oldest first. */
	domainSharesList: () => __TAURI_INVOKE<DomainShare[]>("domain_shares_list"),
	/**
	 *  Shares a local service at a hostname on one of the account's domains, through this
	 *  Mac's tunnel, until it's stopped, `stop_after_minutes` pass, or Teitunnel quits. Never
	 *  replaces a DNS record Teitunnel didn't create.
	 */
	domainSharesStart: (accountId: string, hostname: string, origin: string, stopAfterMinutes: number | null, access: {
	/**  Email addresses, e.g. `me@xyz.com`. */
	emails: string[],
	/**  Email domains, e.g. `xyz.com`. */
	emailDomains: string[],
} | null, hostHeader: HostHeaderChoice) => __TAURI_INVOKE<Outcome>("domain_shares_start", { accountId, hostname, origin, stopAfterMinutes, access, hostHeader }),
	/**  Stops a share on your domain: its route, DNS record and login are removed. */
	domainSharesStop: (accountId: string, hostname: string) => __TAURI_INVOKE<null>("domain_shares_stop", { accountId, hostname }),
	/**  Quick Shares running in terminals (`teitunnel share`), oldest first. */
	quickShareCliList: () => __TAURI_INVOKE<CliShare[]>("quick_share_cli_list"),
	/**  Stops a terminal's Quick Share (asks its `teitunnel` to end). */
	quickShareCliStop: (owner: string) => __TAURI_INVOKE<null>("quick_share_cli_stop", { owner }),
	/**  The cloudflared binary in use, or `null` if none is installed. */
	binaryStatus: () => __TAURI_INVOKE<{
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
} | null>("binary_status"),
	/**  Downloads, verifies and installs the latest cloudflared into the app data folder. */
	binaryInstall: (onProgress: Channel<InstallProgress>) => __TAURI_INVOKE<BinaryInfo>("binary_install", { onProgress }),
	/**  Checks Cloudflare's releases for a newer cloudflared. */
	binaryCheckUpdate: () => __TAURI_INVOKE<UpdateInfo>("binary_check_update"),
	/**  Shows the binary in Finder. */
	binaryReveal: () => __TAURI_INVOKE<null>("binary_reveal"),
	/**  Services listening on this Mac and Docker containers' ports, likely dev servers first. */
	servicesList: () => __TAURI_INVOKE<LocalService[]>("services_list"),
	/**  Starts sharing `origin`. The URL arrives via `EntityChanged` for `quickShares`. */
	quickShareStart: (origin: string, stopAfterMinutes: number | null, hostHeader: HostHeaderChoice) => __TAURI_INVOKE<QuickShare>("quick_share_start", { origin, stopAfterMinutes, hostHeader }),
	/**
	 *  Restarts a share sending `host_header` to its service (`null`: none), for a dev
	 *  server that refuses the public address. The share gets a new URL and is checked
	 *  again once it's live.
	 */
	quickShareSetHostHeader: (id: string, hostHeader: string | null) => __TAURI_INVOKE<QuickShare>("quick_share_set_host_header", { id, hostHeader }),
	/**
	 *  Checks a live share through Cloudflare again (e.g. after changing the dev server's
	 *  config).
	 */
	quickShareCheck: (id: string) => __TAURI_INVOKE<Verification>("quick_share_check", { id }),
	/**  Stops a share. */
	quickShareStop: (id: string) => __TAURI_INVOKE<null>("quick_share_stop", { id }),
	/**  Running shares, newest first. */
	quickShareList: () => __TAURI_INVOKE<QuickShare[]>("quick_share_list"),
	/**  Request counts for a share (polled by the UI while visible). */
	quickShareStats: (id: string) => __TAURI_INVOKE<ShareStats>("quick_share_stats", { id }),
	/**  The newest cloudflared log lines of a share. */
	quickShareLogs: (id: string, limit: number) => __TAURI_INVOKE<LogLine[]>("quick_share_logs", { id, limit }),
	/**  An SVG QR code for `url` (dark modules use `currentColor`). */
	quickShareQr: (url: string) => __TAURI_INVOKE<string>("quick_share_qr", { url }),
	/**  Connected accounts. */
	accountsList: () => __TAURI_INVOKE<Account[]>("accounts_list"),
	/**
	 *  Verifies an API token and connects every account it reaches. The token is stored in
	 *  the keychain and never sent back.
	 */
	accountsAddToken: (token: string) => __TAURI_INVOKE<Account[]>("accounts_add_token", { token }),
	/**  Opens one of Cloudflare's API token pages in the browser. */
	accountsOpenTokenPage: (page: TokenPage) => __TAURI_INVOKE<null>("accounts_open_token_page", { page }),
	/**  Whether `~/.cloudflared/cert.pem` (from `cloudflared tunnel login`) exists. */
	accountsDetectCert: () => __TAURI_INVOKE<boolean>("accounts_detect_cert"),
	/**  Imports the login from `~/.cloudflared/cert.pem` (the file is only read). */
	accountsImportCert: () => __TAURI_INVOKE<Account>("accounts_import_cert"),
	/**  Disconnects an account and deletes its credentials from the keychain. */
	accountsRemove: (id: string) => __TAURI_INVOKE<null>("accounts_remove", { id }),
	/**  What the account's credential can do. */
	accountsCapabilities: (id: string) => __TAURI_INVOKE<Capabilities>("accounts_capabilities", { id }),
	/**  Domains in an account. */
	domainsList: (accountId: string) => __TAURI_INVOKE<Domain[]>("domains_list", { accountId }),
	/**  Whether "Sign in with Cloudflare" (OAuth) is available in this build. */
	accountsOauthAvailable: () => __TAURI_INVOKE<boolean>("accounts_oauth_available"),
	/**
	 *  Signs in with Cloudflare in the browser. The authorize URL is sent on `on_url` (for
	 *  "Copy link" if the browser didn't open); resolves when the browser comes back.
	 */
	accountsOauthSignIn: (onUrl: Channel<string>) => __TAURI_INVOKE<Account[]>("accounts_oauth_sign_in", { onUrl }),
	/**  Cancels a sign-in that's waiting for the browser. */
	accountsOauthCancel: () => __TAURI_INVOKE<void>("accounts_oauth_cancel"),
	/**  This Mac's tunnel and routes in an account. */
	routesOverview: (accountId: string) => __TAURI_INVOKE<RoutesOverview_Serialize>("routes_overview", { accountId }),
	/**
	 *  Plans a change for review, on one of this Mac's tunnels (`tunnel_id`, or the
	 *  default one). Nothing is changed.
	 */
	routesPreview: (accountId: string, tunnelId: string | null, change: Change_Deserialize) => __TAURI_INVOKE<PlanView>("routes_preview", { accountId, tunnelId, change }),
	/**
	 *  Applies a reviewed change. Step progress streams on `on_progress`. Fails with
	 *  `conflict` if anything changed since the preview (preview again).
	 */
	routesApply: (accountId: string, tunnelId: string | null, change: Change_Deserialize, fingerprint: string, confirmed: boolean, onProgress: Channel<Progress>) => __TAURI_INVOKE<Outcome>("routes_apply", { accountId, tunnelId, change, fingerprint, confirmed, onProgress }),
	/**
	 *  Checks a route end to end. With `wait`, transient failures (connector connecting,
	 *  propagation) are retried for up to 30 s, as right after applying.
	 */
	routesVerify: (accountId: string, hostname: string, wait: boolean) => __TAURI_INVOKE<Verification>("routes_verify", { accountId, hostname, wait }),
	/**  An outside edit of this Mac's routes (on any of its tunnels), if there is one. */
	routesDrift: (accountId: string) => __TAURI_INVOKE<{
	/**  Tunnel id. */
	tunnelId: string,
	/**  Version Teitunnel last wrote. */
	appliedVersion: number,
	/**  Version now. */
	currentVersion: number,
	/**  Routes that differ. */
	changes: RuleChange[],
} | null>("routes_drift", { accountId }),
	/**  How each machine behind a load-balanced route does, from Cloudflare's health checks. */
	routesBalanceHealth: (accountId: string, hostname: string) => __TAURI_INVOKE<EndpointHealth[]>("routes_balance_health", { accountId, hostname }),
	/**  Accepts an outside edit as the new baseline ("Keep theirs"). */
	routesKeepTheirs: (accountId: string) => __TAURI_INVOKE<null>("routes_keep_theirs", { accountId }),
	/**  Recent changes in an account, newest first. */
	routesActivity: (accountId: string) => __TAURI_INVOKE<ActivityEntry[]>("routes_activity", { accountId }),
	/**  Every tunnel in the account, this Mac's first. */
	tunnelsList: (accountId: string) => __TAURI_INVOKE<TunnelSummary[]>("tunnels_list", { accountId }),
	/**  Starts this Mac's connector for the account's tunnel. */
	tunnelsStart: (accountId: string) => __TAURI_INVOKE<null>("tunnels_start", { accountId }),
	/**  Stops this Mac's connector for a tunnel. Its routes stop answering until it starts. */
	tunnelsStop: (accountId: string, tunnelId: string) => __TAURI_INVOKE<null>("tunnels_stop", { accountId, tunnelId }),
	/**  Removes a tunnel's stale connections (left by connectors that went away uncleanly). */
	tunnelsClean: (accountId: string, tunnelId: string) => __TAURI_INVOKE<null>("tunnels_clean", { accountId, tunnelId }),
	/**
	 *  cloudflared configurations found on this Mac (`~/.cloudflared/config.yml`, …). Only
	 *  reads; credentials' secrets are never read.
	 */
	importScan: () => __TAURI_INVOKE<LocalSetup_Serialize[]>("import_scan"),
	/**  cloudflared processes on this Mac that Teitunnel didn't start. */
	foreignList: () => __TAURI_INVOKE<ForeignConnector[]>("foreign_list"),
	/**  Stops a cloudflared process Teitunnel didn't start (after re-checking it's one). */
	foreignStop: (pid: number) => __TAURI_INVOKE<null>("foreign_stop", { pid }),
	/**  The newest log lines of this Mac's connector for a tunnel. */
	tunnelsLogs: (tunnelId: string, limit: number) => __TAURI_INVOKE<LogLine[]>("tunnels_logs", { tunnelId, limit }),
	/**
	 *  The newest log lines of a connector anywhere, streamed through Cloudflare. The first
	 *  call starts the stream; it stops by itself once nobody asks for 30 s.
	 */
	tunnelsRemoteLogs: (accountId: string, tunnelId: string, connectorId: string, limit: number) => __TAURI_INVOKE<RemoteLogsView>("tunnels_remote_logs", { accountId, tunnelId, connectorId, limit }),
	/**  Stops a connector's live logs (closing the viewer, or before trying again). */
	tunnelsRemoteLogsStop: (accountId: string, tunnelId: string, connectorId: string) => __TAURI_INVOKE<void>("tunnels_remote_logs_stop", { accountId, tunnelId, connectorId }),
	/**
	 *  The newest log lines about requests for one route (its failed requests, and every
	 *  request when cloudflared logs at debug level).
	 */
	routesLogs: (accountId: string, hostname: string, path: string | null, limit: number) => __TAURI_INVOKE<LogLine[]>("routes_logs", { accountId, hostname, path, limit }),
	/**
	 *  One of this Mac's tunnels (`tunnel_id`, or the default one) and its routes as
	 *  `config.yml`, Docker Compose or Terraform. `None` if this Mac has no such tunnel in
	 *  the account. Never contains a secret.
	 */
	routesExport: (accountId: string, tunnelId: string | null, format: ExportFormat) => __TAURI_INVOKE<{
	/**  Suggested file name, e.g. `config.yml`. */
	fileName: string,
	/**  The file. */
	contents: string,
} | null>("routes_export", { accountId, tunnelId, format }),
	/**  Saves an export to Downloads and shows it in Finder. Returns its path. */
	routesExportSave: (accountId: string, tunnelId: string | null, format: ExportFormat) => __TAURI_INVOKE<string>("routes_export_save", { accountId, tunnelId, format }),
	/**
	 *  This Mac's connector traffic for a tunnel: samples after `since` (ms; the last hour
	 *  without it) and the latest numbers. Polling this keeps sampling at 1 s (D-046).
	 */
	tunnelsTraffic: (tunnelId: string, since: number | null) => __TAURI_INVOKE<{
	/**  Samples newer than the read's `since` (all of them without it), oldest first. */
	series: TrafficSeries,
	/**  Requests since the connector started. */
	totalRequests: number,
	/**  Failed requests since the connector started. */
	totalErrors: number,
	/**  Edge connections now. */
	connections: number,
	/**  Round-trip time to the edge now, in milliseconds. */
	rttMs: number | null,
	/**  Edge locations, e.g. `AMS`. */
	locations: string[],
} | null>("tunnels_traffic", { tunnelId, since }),
	/**  A tunnel's traffic over the last day or week, from per-minute history. */
	tunnelsTrafficHistory: (tunnelId: string, range: HistoryRange) => __TAURI_INVOKE<TrafficSeries>("tunnels_traffic_history", { tunnelId, range }),
	/**
	 *  Whether one of this Mac's connectors (`tunnel_id`, or the default tunnel's) keeps
	 *  running when Teitunnel quits.
	 */
	tunnelsAlwaysOn: (accountId: string, tunnelId: string | null) => __TAURI_INVOKE<AlwaysOn>("tunnels_always_on", { accountId, tunnelId }),
	/**
	 *  Switches one of this Mac's connectors (`tunnel_id`, or the default tunnel's) between
	 *  running with the app and running as a service (keeps running after quit and at
	 *  login), without a gap.
	 */
	tunnelsSetAlwaysOn: (accountId: string, tunnelId: string | null, enabled: boolean) => __TAURI_INVOKE<null>("tunnels_set_always_on", { accountId, tunnelId, enabled }),
	/**
	 *  Runs an existing tunnel of the account on this Mac too (nothing changes in
	 *  Cloudflare), then starts its connector.
	 */
	tunnelsAdopt: (accountId: string, tunnelId: string) => __TAURI_INVOKE<null>("tunnels_adopt", { accountId, tunnelId }),
	/**  Checks cloudflared and every connected account; issues sorted by severity. */
	doctorRun: () => __TAURI_INVOKE<Issue_Serialize[]>("doctor_run"),
	/**
	 *  Ignores (or stops ignoring) Doctor issues by id. Ignored issues are hidden and never
	 *  notify. Every window is told the settings changed.
	 */
	doctorSetIgnored: (ids: string[], ignored: boolean) => __TAURI_INVOKE<Settings>("doctor_set_ignored", { ids, ignored }),
	/**
	 *  Applies every fix that needs no review (owned DNS repairs and orphan cleanup), each
	 *  through a fresh plan; the rest are left for the user.
	 */
	doctorFixSafe: () => __TAURI_INVOKE<FixReport>("doctor_fix_safe"),
	/**  What a diagnostics export would contain (shown before saving). */
	diagnosticsPreview: () => __TAURI_INVOKE<FileSummary[]>("diagnostics_preview"),
	/**
	 *  Saves the diagnostics bundle to Downloads and shows it in Finder. Returns its path.
	 *  With `include_cloudflared`, cloudflared's own report of this machine's connector is
	 *  added as it is (it can take a minute: it runs traceroutes).
	 */
	diagnosticsExport: (includeCloudflared: boolean) => __TAURI_INVOKE<string>("diagnostics_export", { includeCloudflared }),
};

/** Events */
export const events = {
	entityChanged: makeEvent<EntityChanged>("entity-changed"),
	menuAction: makeEvent<MenuAction>("menu-action"),
};

/* Types */
/**  Who may reach a protected route: any of these emails, or anyone at these domains. */
export type AccessRule = {
	/**  Email addresses, e.g. `me@xyz.com`. */
	emails: string[],
	/**  Email domains, e.g. `xyz.com`. */
	emailDomains: string[],
};

/**  A connected Cloudflare account. */
export type Account = {
	/**  Cloudflare account id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  How it was connected. */
	credential: CredentialKind,
	/**  For cert.pem credentials: the only zone the credential works for. */
	limitedZone: string | null,
};

/**  One entry of the activity log. */
export type ActivityEntry = {
	/**  Row id. */
	id: number,
	/**  Milliseconds since the epoch. */
	at: number | null,
	/**  What was asked, e.g. "Add app.xyz.com → http://localhost:3000". */
	summary: string,
	/**  `applied`, `rolledBack` or `partiallyApplied`. */
	outcome: string,
	/**
	 *  Step descriptions and any error, as plain lines (search, and entries from
	 *  before the structured record).
	 */
	detail: string[],
	/**  Kind, hostnames, step states and before/after (absent in older entries). */
	record: ActivityRecord | null,
};

/**  What kind of change an entry records (for filtering). */
export type ActivityKind = 
/**  A route was added. */
"addRoute" | 
/**  A route was changed or renamed. */
"updateRoute" | 
/**  A route was removed. */
"removeRoute" | 
/**  Every route was removed and the tunnel deleted. */
"removeTunnel" | 
/**  Routes were imported from a cloudflared setup. */
"importRoutes" | 
/**  A DNS record was deleted (Doctor cleanup). */
"deleteRecord" | 
/**  Routes were restored after an outside edit. */
"restoreConfig" | 
/**  A login whose route was gone was removed (Doctor cleanup). */
"removeLogin" | 
/**  A private network was shared. */
"addNetwork" | 
/**  A private network stopped being shared. */
"removeNetwork" | 
/**  Another tunnel was created for this Mac. */
"createTunnel" | 
/**  A route started being load balanced. */
"balanceRoute" | 
/**  A route stopped being load balanced. */
"unbalanceRoute";

/**  The structured part of an activity entry. */
export type ActivityRecord = {
	/**  What kind of change. */
	kind: ActivityKind,
	/**  Every hostname involved, sorted. */
	hostnames: string[],
	/**  The tunnel's name. */
	tunnel: string,
	/**  The steps that change something, in order. */
	steps: RecordedStep[],
	/**  What changed, routes first. */
	changes: Delta[],
	/**  What was asked (absent in entries from before messages had keys). */
	summary?: Text | null,
	/**  Why it failed, when it did. */
	error?: Text | null,
	/**  What couldn't be undone after a failure. */
	leftovers?: Text[],
	/**  The routes were applied but this Mac's connector couldn't be started. */
	connectorError?: Text | null,
};

/**  Whether this Mac's connector can run as a service, and whether it does. */
export type AlwaysOn = {
	/**  This system supports Always-on. */
	supported: boolean,
	/**  The connector runs as a service. */
	enabled: boolean,
};

/**
 *  An error as shown to the user: what happened, and what to do about it. The text is
 *  translated by the UI (D-062).
 */
export type AppError = {
	/**  Category for programmatic handling. */
	code: ErrorCode,
	/**  One sentence describing what happened. */
	message: Text,
	/**
	 *  What the user can do about it (boxed: most errors have none, and a small error
	 *  keeps every command's `Result` small).
	 */
	hint: Text | null,
	/**  The input field the error refers to. */
	field: string | null,
};

/**  Static facts about the running app. */
export type AppInfo = {
	/**  App version (semver). */
	version: string,
	/**  Operating system: `macos`, `linux` or `windows`. */
	platform: string,
	/**  CPU architecture, e.g. `aarch64`. */
	arch: string,
	/**  Directory holding the database, logs and managed binaries. */
	dataDir: string,
};

/**  A message argument: a number (formatted for the language) or text. */
export type Arg = 
/**  A number, e.g. a count (a JavaScript number in the UI). */
number | null | 
/**  Anything else, already as text (hostnames, names, versions). */
string;

/**  Where cloudflared comes from and whether it's new enough. */
export type BinaryInfo = {
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
};

/**  Everything a credential can do in one account. */
export type Capabilities = {
	/**  List domains. */
	zonesRead: Grant,
	/**  List tunnels. */
	tunnelsRead: Grant,
	/**  Create and configure tunnels. */
	tunnelsEdit: Grant,
	/**  Access policies (optional feature). */
	accessEdit: Grant,
	/**  DNS editing, per domain. */
	zones: ZoneGrant[],
};

/**  A change the user asks for (or a Doctor fix proposes). */
export type Change = Change_Serialize | Change_Deserialize;

/**  A change the user asks for (or a Doctor fix proposes). */
export type Change_Deserialize = 
/**  Add a route. */
({ type: "addRoute"; 
/**  The route. */
route: RouteInput_Deserialize }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; routes?: never; zoneId?: never } | 
/**  Edit or rename a route. */
({ type: "updateRoute"; 
/**  Current hostname. */
hostname: string; 
/**  Current path. */
path: string | null; 
/**  The new definition. */
route: RouteInput_Deserialize }) & { domain?: never; name?: never; network?: never; recordId?: never; routes?: never; zoneId?: never } | 
/**  Remove a route. */
({ type: "removeRoute"; 
/**  Hostname. */
hostname: string; 
/**  Path. */
path: string | null }) & { domain?: never; name?: never; network?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Remove every route and delete this Mac's tunnel. */
({ type: "removeTunnel" }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Load balance a route across the tunnels that route its hostname. */
({ type: "balanceRoute"; 
/**  Hostname. */
hostname: string }) & { domain?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Stop load balancing a route. */
({ type: "unbalanceRoute"; 
/**  Hostname. */
hostname: string }) & { domain?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Create another tunnel for this Mac. */
({ type: "createTunnel"; 
/**  Its name. */
name: string }) & { domain?: never; hostname?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Undo an outside edit of this Mac's routes. */
({ type: "restoreConfig" }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Remove a login Teitunnel added whose route is gone. */
({ type: "removeLogin"; 
/**  The Access domain, e.g. `app.example.com` or `app.example.com/admin`. */
domain: string }) & { hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Add several routes at once (import from an existing cloudflared setup). */
({ type: "importRoutes"; 
/**  The routes. */
routes: RouteInput_Deserialize[] }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; zoneId?: never } | 
/**  Let WARP clients reach a private range through this Mac's tunnel. */
({ type: "addNetwork"; 
/**  An IP address or CIDR range, e.g. `192.168.1.0/24`. */
network: string }) & { domain?: never; hostname?: never; name?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Stop sharing a private range. */
({ type: "removeNetwork"; 
/**  The range. */
network: string }) & { domain?: never; hostname?: never; name?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Delete one DNS record (an orphan found by the Doctor). */
({ type: "deleteRecord"; 
/**  Zone id. */
zoneId: string; 
/**  The record's name. */
hostname: string; 
/**  Record id. */
recordId: string }) & { domain?: never; name?: never; network?: never; path?: never; route?: never; routes?: never };

/**  A change the user asks for (or a Doctor fix proposes). */
export type Change_Serialize = 
/**  Add a route. */
({ type: "addRoute"; 
/**  The route. */
route: RouteInput_Serialize }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; routes?: never; zoneId?: never } | 
/**  Edit or rename a route. */
({ type: "updateRoute"; 
/**  Current hostname. */
hostname: string; 
/**  Current path. */
path: string | null; 
/**  The new definition. */
route: RouteInput_Serialize }) & { domain?: never; name?: never; network?: never; recordId?: never; routes?: never; zoneId?: never } | 
/**  Remove a route. */
({ type: "removeRoute"; 
/**  Hostname. */
hostname: string; 
/**  Path. */
path: string | null }) & { domain?: never; name?: never; network?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Remove every route and delete this Mac's tunnel. */
({ type: "removeTunnel" }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Load balance a route across the tunnels that route its hostname. */
({ type: "balanceRoute"; 
/**  Hostname. */
hostname: string }) & { domain?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Stop load balancing a route. */
({ type: "unbalanceRoute"; 
/**  Hostname. */
hostname: string }) & { domain?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Create another tunnel for this Mac. */
({ type: "createTunnel"; 
/**  Its name. */
name: string }) & { domain?: never; hostname?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Undo an outside edit of this Mac's routes. */
({ type: "restoreConfig" }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Remove a login Teitunnel added whose route is gone. */
({ type: "removeLogin"; 
/**  The Access domain, e.g. `app.example.com` or `app.example.com/admin`. */
domain: string }) & { hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Add several routes at once (import from an existing cloudflared setup). */
({ type: "importRoutes"; 
/**  The routes. */
routes: RouteInput_Serialize[] }) & { domain?: never; hostname?: never; name?: never; network?: never; path?: never; recordId?: never; route?: never; zoneId?: never } | 
/**  Let WARP clients reach a private range through this Mac's tunnel. */
({ type: "addNetwork"; 
/**  An IP address or CIDR range, e.g. `192.168.1.0/24`. */
network: string }) & { domain?: never; hostname?: never; name?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Stop sharing a private range. */
({ type: "removeNetwork"; 
/**  The range. */
network: string }) & { domain?: never; hostname?: never; name?: never; path?: never; recordId?: never; route?: never; routes?: never; zoneId?: never } | 
/**  Delete one DNS record (an orphan found by the Doctor). */
({ type: "deleteRecord"; 
/**  Zone id. */
zoneId: string; 
/**  The record's name. */
hostname: string; 
/**  Record id. */
recordId: string }) & { domain?: never; name?: never; network?: never; path?: never; route?: never; routes?: never };

/**  A terminal's live Quick Share. */
export type CliShare = {
	/**  The CLI process (`<pid>-<start time>`). */
	owner: string,
	/**  What's shared. */
	origin: string,
	/**  Its public URL. */
	url: string,
	/**  When it started (milliseconds since the epoch). */
	startedAt: number | null,
	/**  When it stops by itself (milliseconds since the epoch). */
	stopAt: number | null,
};

/**  Where the CLI stands. */
export type CliState = 
/**  This build doesn't include it (development builds). */
{ state: "unavailable" } | 
/**  The package manager already put it on the PATH. */
{ state: "packaged"; path: string } | 
/**  Teitunnel installed it here. */
{ state: "installed"; path: string } | 
/**
 *  Not installed. `path`: where installing puts it; `command`: what to run instead
 *  when Teitunnel can't write there itself.
 */
{ state: "notInstalled"; path: string | null; command: string | null } | 
/**  Something else is at that path; Teitunnel leaves it alone. */
{ state: "taken"; path: string };

/**  What a visitor runs to reach a non-HTTP route. */
export type ClientAccess = {
	/**  The protocol. */
	protocol: ClientProtocol,
	/**  The command to run (SSH: to connect; others: to open the local port). */
	command: string,
	/**  Where the visitor's app connects once the command runs (`None` for SSH). */
	localAddress: string | null,
	/**  An `~/.ssh/config` entry, so plain `ssh <hostname>` works (SSH only). */
	sshConfig: string | null,
};

/**  The protocol a non-HTTP route carries. */
export type ClientProtocol = 
/**  SSH. */
"ssh" | 
/**  Remote Desktop. */
"rdp" | 
/**  Windows file sharing. */
"smb" | 
/**  Any TCP service (a database, …). */
"tcp";

/**  One edge connection of a connector. */
export type ConnectionView = {
	/**  Edge location, e.g. `ams01`. */
	colo: string,
	/**  When it connected (RFC 3339). */
	openedAt: string,
};

/**  Lifecycle of one connector (ARCHITECTURE §5.1). */
export type ConnectorState = 
/**  Not running. */
{ state: "stopped" } | 
/**  The process is being spawned. */
{ state: "starting" } | 
/**  Running, but no edge connection yet. */
{ state: "connecting" } | 
/**  Serving traffic. */
{ state: "healthy"; 
/**  Registered edge connections. */
connections: number } | 
/**
 *  Running with no edge connections after having had some (or after the start
 *  timeout).
 */
{ state: "degraded" } | 
/**  Exited unexpectedly; restarts after a backoff. */
{ state: "crashed"; 
/**  Restart attempt number (1-based). */
attempt: number; 
/**  Milliseconds until the restart. */
retry_in_ms: number; 
/**  Exit code, when there was one. */
exit_code: number | null } | 
/**  Crashed too often in a short time; not restarted automatically. */
{ state: "crashLoop"; 
/**  Exit code of the last crash. */
exit_code: number | null } | 
/**  Shutting down. */
{ state: "stopping" };

/**  One machine running a tunnel (a cloudflared process), with its edge connections. */
export type ConnectorView = {
	/**  Connector id. */
	id: string,
	/**  cloudflared version. */
	version: string,
	/**  Public IP it connects from. */
	originIp: string,
	/**  It's this Mac's connector. */
	thisMac: boolean,
	/**  Edge connections, by location. */
	connections: ConnectionView[],
};

/**  How an account was connected. */
export type CredentialKind = 
/**  A user API token. */
"apiToken" | 
/**  OAuth sign-in (refresh token in the keychain). */
"oauth" | 
/**  Imported from `cloudflared tunnel login` (cert.pem); one zone only. */
"certPem";

/**  One thing that changed: absent `before` means added, absent `after` removed. */
export type Delta = {
	/**  Route or DNS record. */
	area: DeltaArea,
	/**  Public hostname. */
	hostname: string,
	/**  Path rule, for routes that have one. */
	path: string | null,
	/**  What it was. */
	before: Text | null,
	/**  What it became. */
	after: Text | null,
};

/**  Where a change happened. */
export type DeltaArea = 
/**  The tunnel's routes (ingress). */
"route" | 
/**  A DNS record. */
"dns" | 
/**  A private network route. */
"network" | 
/**  A route's login (Cloudflare Access). */
"access" | 
/**  A route's load balancing. */
"loadBalancing";

/**  A dev server that checks the Host header. */
export type DevServer = 
/**  Vite 5.4.12+ / 6.0.9+ (`server.allowedHosts`), also Laravel's and Remix's. */
"vite" | 
/**  SvelteKit (Vite). */
"svelteKit" | 
/**  Astro (Vite). */
"astro" | 
/**  Nuxt (Vite). */
"nuxt" | 
/**  Angular CLI (`ng serve`, Vite or webpack). */
"angular" | 
/**  webpack-dev-server (webpack, Create React App, Vue CLI). */
"webpack" | 
/**  Next.js 15.2+ (`allowedDevOrigins`). */
"next" | 
/**  Rails 6+ (`ActionDispatch::HostAuthorization`). */
"rails" | 
/**  Django (`ALLOWED_HOSTS`). */
"django";

/**  Whether a route's DNS record points at this Mac's tunnel. */
export type DnsState = 
/**  A proxied CNAME to the tunnel. */
{ state: "ok" } | 
/**  No record. */
{ state: "missing" } | 
/**  A record pointing somewhere else (or not proxied). */
{ state: "elsewhere"; 
/**  What it points at. */
content: string };

/**  A domain in a connected account. */
export type Domain = {
	/**  Zone id. */
	id: string,
	/**  Domain name. */
	name: string,
	/**  Setup state. */
	status: DomainStatus,
	/**  Cloudflare nameservers to set at the registrar. */
	nameServers: string[],
	/**  Nameservers currently at the registrar (before the switch). */
	originalNameServers: string[],
	/**  Plan name. */
	plan: string | null,
	/**  Whether the proxy is paused. */
	paused: boolean,
};

/**  A temporary route, as remembered. */
export type DomainShare = {
	/**  Account id. */
	accountId: string,
	/**  The public hostname. */
	hostname: string,
	/**  The service shared, as the user gave it. */
	origin: string,
	/**  [`APP_OWNER`], or the CLI process that started it. */
	owner: string,
	/**  When it ends by itself (milliseconds since the epoch). */
	expiresAt: number | null,
	/**  When it started (milliseconds since the epoch). */
	createdAt: number | null,
};

/**  Where a domain is in its setup. */
export type DomainStatus = 
/**  Active on Cloudflare: routes can use it. */
"active" | 
/**  Waiting for the registrar to switch nameservers. */
"pending" | 
/**  Nameservers moved away from Cloudflare. */
"moved" | 
/**  Being set up, or a state we don't know. */
"other";

/**  An outside edit of this Mac's tunnel configuration. */
export type Drift = {
	/**  Tunnel id. */
	tunnelId: string,
	/**  Version Teitunnel last wrote. */
	appliedVersion: number,
	/**  Version now. */
	currentVersion: number,
	/**  Routes that differ. */
	changes: RuleChange[],
};

/**
 *  How one machine's tunnel behind a balanced route does, from Cloudflare's health
 *  checks in each region.
 */
export type EndpointHealth = {
	/**  Tunnel id. */
	tunnelId: string,
	/**  The endpoint's name (the tunnel's). */
	name: string,
	/**  Whether it gets traffic. */
	enabled: boolean,
	/**  Regions whose checks pass. */
	healthyRegions: number,
	/**  Regions that checked it (0 until the first checks come in). */
	regions: number,
	/**  Why checks fail, in Cloudflare's words (e.g. "HTTP timeout occurred"). */
	reason: string | null,
};

/**  Emitted after anything changes, so the UI can invalidate the affected queries. */
export type EntityChanged = {
	/**  What kind of entity changed. */
	kind: EntityKind,
	/**  Which one, when a single entity changed. */
	id: string | null,
};

/**  Kinds of entities the UI caches. Each maps to TanStack Query keys on the frontend. */
export type EntityKind = 
/**  App settings. */
"settings" | 
/**  Quick Shares (list, status, URL). */
"quickShares" | 
/**  Connected Cloudflare accounts (and their domains). */
"accounts" | 
/**  Routes and this Mac's tunnel (id: the account). */
"routes" | 
/**  App updates. */
"updates";

/**  Machine-readable error category. The frontend branches on this, never on `message`. */
export type ErrorCode = 
/**  An unexpected failure. The message is safe to show; details are in the app log. */
"internal" | 
/**  The input was rejected; `field` names the offending field. */
"invalidInput" | 
/**  The thing acted on doesn't exist (any more). */
"notFound" | 
/**  cloudflared isn't installed. */
"cloudflaredMissing" | 
/**  Busy or exhausted; retrying later may work. */
"unavailable" | 
/**
 *  Something changed since the user looked, or a confirmation is missing: refresh
 *  the preview.
 */
"conflict" | 
/**  The Cloudflare credential lacks a permission. */
"permissionDenied";

/**  A rendered export. */
export type ExportFile = {
	/**  Suggested file name, e.g. `config.yml`. */
	fileName: string,
	/**  The file. */
	contents: string,
};

/**  What to export as. */
export type ExportFormat = 
/**  A cloudflared `config.yml` (ingress rules). */
"configYaml" | 
/**  A Docker Compose service running the tunnel. */
"dockerCompose" | 
/**  Terraform for the Cloudflare provider v5, with `import` blocks. */
"terraform";

/**  Why a route doesn't work. */
export type Failure = 
/**  There's no DNS record for the hostname. */
{ type: "noRecord" } | 
/**  The record exists but doesn't point at this Mac's tunnel (or isn't proxied). */
{ type: "recordElsewhere"; 
/**  What it points at. */
content: string } | 
/**  The edge couldn't be reached (network, firewall). */
{ type: "edgeUnreachable"; 
/**  The error. */
message: string } | 
/**  The certificate doesn't cover the hostname (Universal SSL covers one level). */
{ type: "certificateNotCovered" } | 
/**  Cloudflare doesn't know the hostname yet (error 1001), usually propagation. */
{ type: "notOnCloudflareYet" } | 
/**  No connector is connected to the tunnel (error 1033). */
{ type: "noConnector" } | 
/**  The record points at a tunnel that doesn't serve it (error 1016 / 530). */
{ type: "tunnelMismatch" } | 
/**  The connector couldn't reach the origin (502). */
{ type: "originUnreachable"; 
/**  Whether something listens on the origin's local port (None: not local). */
listening: boolean | null; 
/**  The origin's port, when it has one. */
port: number | null } | 
/**  The origin didn't answer in time (504). */
{ type: "originTimeout" } | 
/**  A dev server refused the public address (its Host or Origin check). */
{ type: "hostRejected"; 
/**  Which server, and the ways to fix it. */
rejection: HostRejection } | 
/**
 *  Cloudflare refused a request body over its limit (413): 100 MB on the Free and
 *  Pro plans.
 */
{ type: "bodyTooLarge" } | 
/**  A Quick Share had 200 requests in flight, its limit (429). */
{ type: "tooManyRequests" };

/**  What the preview shows for a file. */
export type FileSummary = {
	/**  Path inside the archive. */
	name: string,
	/**  Size in bytes. */
	size: number,
	/**  The first lines, for a quick look. */
	excerpt: string,
};

/**  A way to fix an issue. */
export type Fix = Fix_Serialize | Fix_Deserialize;

/**  What "Fix all safe issues" did. */
export type FixReport = {
	/**  Issues fixed. */
	fixed: number,
	/**  Issues left for the user (their fix needs a confirmation or a decision). */
	skipped: number,
	/**  Fixes that failed (and were rolled back), with why. */
	failed: string[],
};

/**  A way to fix an issue. */
export type Fix_Deserialize = 
/**  A change in Cloudflare, previewed as a plan before it's applied. */
({ type: "change"; 
/**  Button title, e.g. "Fix the DNS Record". */
label: Text; 
/**  The change. */
change: Change_Deserialize }) & { accountId?: never; tunnelId?: never } | 
/**  Install (or update) the managed cloudflared. */
({ type: "installBinary" }) & { accountId?: never; change?: never; label?: never; tunnelId?: never } | 
/**  Start this Mac's connector. */
({ type: "startConnector"; 
/**  Account. */
accountId: string }) & { change?: never; label?: never; tunnelId?: never } | 
/**  Accept an outside edit of this Mac's routes. */
({ type: "keepTheirs"; 
/**  Account. */
accountId: string }) & { change?: never; label?: never; tunnelId?: never } | 
/**  Create a token with the right permissions. */
({ type: "reconnect" }) & { accountId?: never; change?: never; label?: never; tunnelId?: never } | 
/**  Remove a tunnel's stale connections. */
({ type: "cleanConnections"; 
/**  Account. */
accountId: string; 
/**  Tunnel. */
tunnelId: string }) & { change?: never; label?: never };

/**  A way to fix an issue. */
export type Fix_Serialize = 
/**  A change in Cloudflare, previewed as a plan before it's applied. */
({ type: "change"; 
/**  Button title, e.g. "Fix the DNS Record". */
label: Text; 
/**  The change. */
change: Change_Serialize }) & { accountId?: never; tunnelId?: never } | 
/**  Install (or update) the managed cloudflared. */
({ type: "installBinary" }) & { accountId?: never; change?: never; label?: never; tunnelId?: never } | 
/**  Start this Mac's connector. */
({ type: "startConnector"; 
/**  Account. */
accountId: string }) & { change?: never; label?: never; tunnelId?: never } | 
/**  Accept an outside edit of this Mac's routes. */
({ type: "keepTheirs"; 
/**  Account. */
accountId: string }) & { change?: never; label?: never; tunnelId?: never } | 
/**  Create a token with the right permissions. */
({ type: "reconnect" }) & { accountId?: never; change?: never; label?: never; tunnelId?: never } | 
/**  Remove a tunnel's stale connections. */
({ type: "cleanConnections"; 
/**  Account. */
accountId: string; 
/**  Tunnel. */
tunnelId: string }) & { change?: never; label?: never };

/**  A cloudflared process Teitunnel doesn't manage. */
export type ForeignConnector = {
	/**  Process id. */
	pid: number,
	/**  The command line, with tokens replaced by `[redacted]`. */
	command: string,
	/**  What it's doing. */
	mode: ForeignMode,
	/**  Started by launchd (a service) rather than a terminal. */
	service: boolean,
	/**  Its metrics address, when it has one. */
	metrics: string | null,
	/**  Edge connections reported by `/ready` (None: no metrics server answered). */
	connections: number | null,
};

/**  What a foreign cloudflared is doing. */
export type ForeignMode = 
/**  `tunnel --url …`: a Quick Tunnel. */
{ type: "quickTunnel"; 
/**  The local origin. */
origin: string } | 
/**  `tunnel run [name]`, with a token or a config. */
{ type: "named"; 
/**  The tunnel name or id, when given on the command line. */
tunnel: string | null; 
/**  The config file, when given. */
config: string | null } | 
/**  Something else (`access`, `proxy-dns`, …). */
{ type: "other" };

/**  One route found in a config file. */
export type FoundRoute = FoundRoute_Serialize | FoundRoute_Deserialize;

/**  One route found in a config file. */
export type FoundRoute_Deserialize = {
	/**  Hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Service, e.g. `http://localhost:3000`. */
	service: string,
	/**  Its origin settings (the file's own `originRequest` merged with the rule's). */
	options: OriginOptions_Deserialize,
	/**  Why it can't be imported, if it can't. */
	unsupported: Text | null,
};

/**  One route found in a config file. */
export type FoundRoute_Serialize = {
	/**  Hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Service, e.g. `http://localhost:3000`. */
	service: string,
	/**  Its origin settings (the file's own `originRequest` merged with the rule's). */
	options: OriginOptions_Serialize,
	/**  Why it can't be imported, if it can't. */
	unsupported: Text | null,
};

/**  The result of probing one permission. */
export type Grant = 
/**  Allowed. */
"yes" | 
/**  Not allowed. */
"no" | 
/**  Couldn't be checked right now. */
"unknown";

/**  A page of help on the web. */
export type HelpLink = 
/**  Teitunnel's documentation. */
"docs" | 
/**  Cloudflare Tunnel's documentation. */
"cloudflareDocs" | 
/**  Release notes. */
"releaseNotes" | 
/**  Report an issue. */
"reportIssue";

/**  A span of persisted history. */
export type HistoryRange = 
/**  The last 24 hours, in 5-minute buckets. */
"day" | 
/**  The last 7 days, in 30-minute buckets. */
"week";

/**  A Host header a share sends to its service. */
export type HostHeader = {
	/**  The value, e.g. `localhost:5173`. */
	value: string,
	/**
	 *  Set by Teitunnel because the service is this dev server, which refuses unknown
	 *  addresses (`None`: the user asked for it).
	 */
	autoFor: DevServer | null,
};

/**  Which Host header a new share sends. */
export type HostHeaderChoice = 
/**
 *  The service's own address when it's a dev server that needs it and where that's
 *  safe ([`dev_server::default_host_header`]); otherwise none.
 */
{ mode: "auto" } | 
/**  Leave the Host header as the visitor's browser sent it. */
{ mode: "off" } | 
/**  Send this value. */
{ mode: "set"; 
/**  E.g. `localhost:5173`. */
value: string };

/**  A dev server refused a request for the public address. */
export type HostRejection = {
	/**  Which server. */
	server: DevServer,
	/**  The public hostname it refused. */
	host: string,
	/**
	 *  The Host header that makes it answer (the origin's own address), when sending it
	 *  helps and isn't sent already.
	 */
	hostHeader: string | null,
	/**
	 *  Sending that header breaks nothing (see [`DevServer::host_header_safe`]). When
	 *  false, the config line is the recommended fix.
	 */
	hostHeaderSafe: boolean,
	/**  The file the config line goes in. */
	configFile: string,
	/**  The line that allows the address. */
	configLine: string,
};

/**  Install progress, streamed to the webview. */
export type InstallProgress = 
/**  Downloading: bytes received of total. */
{ step: "downloading"; 
/**  Bytes received. */
received: number; 
/**  Total bytes. */
total: number } | 
/**  Checking checksums and the code signature. */
{ step: "verifying" } | 
/**  Moving the binary into place. */
{ step: "installing" };

/**  A detected problem. */
export type Issue = Issue_Serialize | Issue_Deserialize;

/**  A detected problem. */
export type Issue_Deserialize = {
	/**  Stable id (check, account, subject), so "Ignore" survives restarts. */
	id: string,
	/**  Which check found it, e.g. `dns.missing`. */
	check: string,
	/**  How bad it is. */
	severity: Severity,
	/**  The account it's in, if any. */
	accountId: string | null,
	/**  What it's about, e.g. a hostname or a tunnel name (stable: part of `id`). */
	subject: string,
	/**  `subject` as shown to the user. */
	label: Text,
	/**  One line. */
	title: Text,
	/**  What it means and what to do. */
	detail: Text,
	/**  Supporting facts (records, states). */
	evidence: Text[],
	/**  Fixes, the recommended one first. */
	fixes: Fix_Deserialize[],
	/**  The tunnel of this Mac's it's about, when not the default one (a fix applies there). */
	tunnelId: string | null,
};

/**  A detected problem. */
export type Issue_Serialize = {
	/**  Stable id (check, account, subject), so "Ignore" survives restarts. */
	id: string,
	/**  Which check found it, e.g. `dns.missing`. */
	check: string,
	/**  How bad it is. */
	severity: Severity,
	/**  The account it's in, if any. */
	accountId: string | null,
	/**  What it's about, e.g. a hostname or a tunnel name (stable: part of `id`). */
	subject: string,
	/**  `subject` as shown to the user. */
	label: Text,
	/**  One line. */
	title: Text,
	/**  What it means and what to do. */
	detail: Text,
	/**  Supporting facts (records, states). */
	evidence: Text[],
	/**  Fixes, the recommended one first. */
	fixes: Fix_Serialize[],
	/**  The tunnel of this Mac's it's about, when not the default one (a fix applies there). */
	tunnelId: string | null,
};

/**  A TCP port something on this machine is listening on. */
export type LocalService = {
	/**  The port. */
	port: number,
	/**  Whether it listens on all interfaces (vs. loopback only). */
	allInterfaces: boolean,
	/**  Owning process id. */
	pid: number,
	/**  Process name, e.g. `node`. */
	process: string,
	/**  What it looks like, e.g. a Vite dev server. */
	kind: ServiceKind,
	/**  Project the process runs in (from its working directory), e.g. `my-app`. */
	project: string | null,
	/**  Suggested origin URL, e.g. `http://localhost:5173`. */
	origin: string,
};

/**  A cloudflared configuration found on disk. */
export type LocalSetup = LocalSetup_Serialize | LocalSetup_Deserialize;

/**  A cloudflared configuration found on disk. */
export type LocalSetup_Deserialize = {
	/**  The config file. */
	configPath: string,
	/**  `tunnel:` (a UUID or a name). */
	tunnel: string | null,
	/**  The Cloudflare account the credentials belong to. */
	accountId: string | null,
	/**  The tunnel id from the credentials file. */
	tunnelId: string | null,
	/**  Routes (hostname rules) in order. */
	routes: FoundRoute_Deserialize[],
	/**
	 *  The file has settings for every route (`originRequest`) that Teitunnel can't
	 *  carry over (the ones it can are merged into each route).
	 */
	hasGlobalOptions: boolean,
	/**  Problems reading the file. */
	problem: Text | null,
};

/**  A cloudflared configuration found on disk. */
export type LocalSetup_Serialize = {
	/**  The config file. */
	configPath: string,
	/**  `tunnel:` (a UUID or a name). */
	tunnel: string | null,
	/**  The Cloudflare account the credentials belong to. */
	accountId: string | null,
	/**  The tunnel id from the credentials file. */
	tunnelId: string | null,
	/**  Routes (hostname rules) in order. */
	routes: FoundRoute_Serialize[],
	/**
	 *  The file has settings for every route (`originRequest`) that Teitunnel can't
	 *  carry over (the ones it can are merged into each route).
	 */
	hasGlobalOptions: boolean,
	/**  Problems reading the file. */
	problem: Text | null,
};

/**  One cloudflared log line, for the log drawer. */
export type LogLine = {
	/**  Timestamp as printed by cloudflared. */
	time: string | null,
	/**  `debug`, `info`, `warn`, `error`, `fatal` or `raw`. */
	level: string,
	/**  The message. */
	message: string,
	/**  The `error` field, if any. */
	error: string | null,
};

/**  Emitted when a menu-bar item that the webview handles is chosen. */
export type MenuAction = {
	/**  The chosen command. */
	command: MenuCommand,
};

/**  A menu-bar command the webview handles (navigation, panes, palette). */
export type MenuCommand = 
/**  File ▸ New Route (⌘N). */
"newRoute" | 
/**  File ▸ New Quick Share (⇧⌘N). */
"newQuickShare" | 
/**  View ▸ Toggle Sidebar (⌥⌘S). */
"toggleSidebar" | 
/**  View ▸ Toggle Inspector (⌥⌘I). */
"toggleInspector" | 
/**  View ▸ Refresh (⌘R). */
"refresh" | 
/**  View ▸ Command Palette (⌘K). */
"commandPalette" | 
/**  View ▸ Overview (⌘1). */
"goOverview" | 
/**  View ▸ Routes (⌘2). */
"goRoutes" | 
/**  View ▸ Quick Share (⌘3). */
"goQuickShare" | 
/**  View ▸ Domains (⌘4). */
"goDomains" | 
/**  View ▸ Tunnels (⌘5). */
"goTunnels" | 
/**  View ▸ Activity (⌘6). */
"goActivity" | 
/**  View ▸ Doctor (⌘7). */
"goDoctor" | 
/**  Quit was chosen while routes run through the app: ask what to do. */
"confirmQuit" | 
/**  Help ▸ Export Diagnostics… */
"exportDiagnostics";

/**  A private network shared through this Mac's tunnel. */
export type NetworkView = {
	/**  The range, e.g. `192.168.1.0/24`. */
	network: string,
	/**
	 *  In private address space (a public range takes those addresses over for WARP
	 *  clients).
	 */
	private: boolean,
	/**  Teitunnel added it (otherwise it was added in the dashboard or with cloudflared). */
	owned: boolean,
};

/**  Origin settings of a route. `None`/`false` means cloudflared's default. */
export type OriginOptions = OriginOptions_Serialize | OriginOptions_Deserialize;

/**  Origin settings of a route. `None`/`false` means cloudflared's default. */
export type OriginOptions_Deserialize = {
	/**  Host header sent to the origin (e.g. a dev server that checks it). */
	httpHostHeader?: string | null,
	/**  Hostname expected on the origin's TLS certificate. */
	originServerName?: string | null,
	/**  Use the request's hostname as the TLS server name. */
	matchSNItoHost?: boolean,
	/**  Accept any certificate from the origin (self-signed ones). */
	noTLSVerify?: boolean,
	/**  Certificate authority file for the origin's certificate (absolute path). */
	caPool?: string | null,
	/**  Speak HTTP/2 to the origin (HTTPS origins). */
	http2Origin?: boolean,
	/**  Don't use chunked transfer encoding (some WSGI servers need this). */
	disableChunkedEncoding?: boolean,
	/**  Seconds to wait for a TCP connection (default 30). */
	connectTimeout?: number | null,
	/**  Seconds to wait for the TLS handshake (default 10). */
	tlsTimeout?: number | null,
	/**  Seconds between TCP keepalive packets (default 30). */
	tcpKeepAlive?: number | null,
	/**  Seconds before an idle keepalive connection closes (default 90). */
	keepAliveTimeout?: number | null,
	/**  Idle keepalive connections kept open (default 100). */
	keepAliveConnections?: number | null,
	/**  Don't fall back between IPv4 and IPv6. */
	noHappyEyeballs?: boolean,
	/**  Proxy type for TCP origins: `socks` for a SOCKS5 proxy. */
	proxyType?: string | null,
};

/**  Origin settings of a route. `None`/`false` means cloudflared's default. */
export type OriginOptions_Serialize = {
	/**  Host header sent to the origin (e.g. a dev server that checks it). */
	httpHostHeader?: string | null,
	/**  Hostname expected on the origin's TLS certificate. */
	originServerName?: string | null,
	/**  Use the request's hostname as the TLS server name. */
	matchSNItoHost?: boolean,
	/**  Accept any certificate from the origin (self-signed ones). */
	noTLSVerify?: boolean,
	/**  Certificate authority file for the origin's certificate (absolute path). */
	caPool?: string | null,
	/**  Speak HTTP/2 to the origin (HTTPS origins). */
	http2Origin?: boolean,
	/**  Don't use chunked transfer encoding (some WSGI servers need this). */
	disableChunkedEncoding?: boolean,
	/**  Seconds to wait for a TCP connection (default 30). */
	connectTimeout?: number | null,
	/**  Seconds to wait for the TLS handshake (default 10). */
	tlsTimeout?: number | null,
	/**  Seconds between TCP keepalive packets (default 30). */
	tcpKeepAlive?: number | null,
	/**  Seconds before an idle keepalive connection closes (default 90). */
	keepAliveTimeout?: number | null,
	/**  Idle keepalive connections kept open (default 100). */
	keepAliveConnections?: number | null,
	/**  Don't fall back between IPv4 and IPv6. */
	noHappyEyeballs?: boolean,
	/**  Proxy type for TCP origins: `socks` for a SOCKS5 proxy. */
	proxyType?: string | null,
};

/**
 *  An HTTP(S) origin cloudflared can proxy to, e.g. `http://localhost:3000`.
 * 
 *  Parsing is forgiving about what people type: `3000`, `:3000`, `localhost:3000`,
 *  `127.0.0.1:8080` and full URLs all work. Paths and query strings are dropped;
 *  cloudflared proxies the whole host.
 */
export type OriginUrl = string;

/**  How applying ended. */
export type Outcome = 
/**  Every step succeeded. */
{ type: "applied"; 
/**  This Mac's tunnel afterwards (None once deleted). */
tunnelId: string | null; 
/**  Hostnames to verify next. */
verify: string[]; 
/**  The connector couldn't be started (the routes are configured, though). */
connectorError: Text | null } | 
/**  A step failed and everything done before it was undone. */
{ type: "rolledBack"; 
/**  Index of the failed step. */
failedStep: number; 
/**  Why it failed. */
error: Text } | 
/**  A step failed and some earlier changes couldn't be undone. */
{ type: "partiallyApplied"; 
/**  Index of the failed step. */
failedStep: number; 
/**  Why it failed. */
error: Text; 
/**  What was left in place. */
leftovers: Text[] };

/**  A plan, as shown in the preview. */
export type PlanView = {
	/**  Steps in order (empty: nothing to change). */
	steps: StepView[],
	/**  Things to review. */
	warnings: Warning[],
	/**  Confirmation needed (touches records Teitunnel didn't create). */
	requiresConfirmation: boolean,
	/**  Pass back to apply, so a change made meanwhile is caught. */
	fingerprint: string,
};

/**  A progress update for the step at `step` (index into the plan). */
export type Progress = {
	/**  Step index. */
	step: number,
	/**  Its state. */
	state: StepState,
};

/**  A running Quick Share, as the UI sees it. */
export type QuickShare = {
	/**  Identifier. */
	id: string,
	/**  The local service being shared. */
	origin: OriginUrl,
	/**  The public URL, once cloudflared has one. */
	url: string | null,
	/**  Current status. */
	status: ShareStatus,
	/**
	 *  Start time, milliseconds since the Unix epoch.
	 * 
	 *  Exported to TypeScript as `number` (values stay far below 2^53). The `u32` is
	 *  only a type hint for specta, which exports `u64` as bigint and `f64` as nullable.
	 */
	startedAt: number,
	/**  When it stops by itself, milliseconds since the Unix epoch. */
	stopAt: number | null,
	/**  The Host header sent to the service, if any. */
	hostHeader: HostHeader | null,
	/**  The check through Cloudflare once the share is live (`None` until then). */
	check: Verification | null,
};

/**  A step of the applied plan and how it ended. */
export type RecordedStep = {
	/**  The step as previewed (with its command). */
	step: StepView,
	/**  Its final state. */
	state: StepState,
};

/**  Where a session is. */
export type RemoteLogState = 
/**  Getting a token and connecting. */
{ state: "connecting" } | 
/**  Receiving the connector's logs. */
{ state: "streaming" } | 
/**  Stopped for good; stop the session and read again to retry. */
{ state: "ended"; 
/**  Why, in a sentence. */
message: Text };

/**  A connector's live logs, when it runs on another machine. */
export type RemoteLogsView = {
	/**  Where the stream is. */
	state: RemoteLogState,
	/**  The newest lines, oldest first. */
	lines: LogLine[],
};

/**  A route as typed in the add/edit sheet. */
export type RouteInput = RouteInput_Serialize | RouteInput_Deserialize;

/**  A route as typed in the add/edit sheet. */
export type RouteInput_Deserialize = {
	/**  Public hostname, e.g. `app.example.com`. */
	hostname: string,
	/**  Optional path regex, e.g. `^/api`. */
	path: string | null,
	/**  Origin, e.g. `3000` or `http://localhost:3000`. */
	origin: string,
	/**
	 *  Require a login for these people. On an edit, `None` removes the login
	 *  Teitunnel added; on an add, it leaves any existing login alone.
	 */
	access?: AccessRule | null,
	/**  Origin settings. On an edit, `None` keeps the route's current ones. */
	options?: OriginOptions_Deserialize | null,
};

/**  A route as typed in the add/edit sheet. */
export type RouteInput_Serialize = {
	/**  Public hostname, e.g. `app.example.com`. */
	hostname: string,
	/**  Optional path regex, e.g. `^/api`. */
	path: string | null,
	/**  Origin, e.g. `3000` or `http://localhost:3000`. */
	origin: string,
	/**
	 *  Require a login for these people. On an edit, `None` removes the login
	 *  Teitunnel added; on an add, it leaves any existing login alone.
	 */
	access: AccessRule | null,
	/**  Origin settings. On an edit, `None` keeps the route's current ones. */
	options: OriginOptions_Serialize | null,
};

/**  One route of this Mac's tunnel. */
export type RouteView = RouteView_Serialize | RouteView_Deserialize;

/**  One route of this Mac's tunnel. */
export type RouteView_Deserialize = {
	/**  Public hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Where traffic goes. */
	origin: string,
	/**  Whether the origin is on this Mac. */
	local: boolean,
	/**  The zone (domain) it belongs to. */
	zone: string | null,
	/**  Its DNS record. */
	dns: DnsState,
	/**  Who may reach it, when Teitunnel added a login. */
	access: AccessRule | null,
	/**  What visitors run to reach it, for SSH, RDP, SMB and TCP routes. */
	client: ClientAccess | null,
	/**  The tunnel of this Mac's that carries it. */
	tunnelId: string | null,
	/**  A share on your domain: removed when the share stops. */
	temporary: boolean,
	/**  Load balanced across tunnels (Cloudflare Load Balancing). */
	balanced: boolean,
	/**  Its origin settings. */
	options: OriginOptions_Deserialize,
};

/**  One route of this Mac's tunnel. */
export type RouteView_Serialize = {
	/**  Public hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Where traffic goes. */
	origin: string,
	/**  Whether the origin is on this Mac. */
	local: boolean,
	/**  The zone (domain) it belongs to. */
	zone: string | null,
	/**  Its DNS record. */
	dns: DnsState,
	/**  Who may reach it, when Teitunnel added a login. */
	access: AccessRule | null,
	/**  What visitors run to reach it, for SSH, RDP, SMB and TCP routes. */
	client: ClientAccess | null,
	/**  The tunnel of this Mac's that carries it. */
	tunnelId: string | null,
	/**  A share on your domain: removed when the share stops. */
	temporary: boolean,
	/**  Load balanced across tunnels (Cloudflare Load Balancing). */
	balanced: boolean,
	/**  Its origin settings. */
	options: OriginOptions_Serialize,
};

/**  Everything the Routes view shows for an account. */
export type RoutesOverview = RoutesOverview_Serialize | RoutesOverview_Deserialize;

/**  Everything the Routes view shows for an account. */
export type RoutesOverview_Deserialize = {
	/**  This Mac's default tunnel, if it has one. */
	tunnel: TunnelView | null,
	/**  Every tunnel of this Mac's in the account, the default first, then by name. */
	tunnels: TunnelView[],
	/**  Routes, sorted by domain then hostname. */
	routes: RouteView_Deserialize[],
	/**  Domains routes can use. */
	zones: ZoneRef[],
	/**
	 *  Private networks shared through this Mac's tunnel, sorted; `None` when the
	 *  credential can't read them.
	 */
	networks: NetworkView[] | null,
};

/**  Everything the Routes view shows for an account. */
export type RoutesOverview_Serialize = {
	/**  This Mac's default tunnel, if it has one. */
	tunnel: TunnelView | null,
	/**  Every tunnel of this Mac's in the account, the default first, then by name. */
	tunnels: TunnelView[],
	/**  Routes, sorted by domain then hostname. */
	routes: RouteView_Serialize[],
	/**  Domains routes can use. */
	zones: ZoneRef[],
	/**
	 *  Private networks shared through this Mac's tunnel, sorted; `None` when the
	 *  credential can't read them.
	 */
	networks: NetworkView[] | null,
};

/**  One route that differs between what Teitunnel wrote and what's there now. */
export type RuleChange = {
	/**  Hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  The service Teitunnel wrote (None: added elsewhere). */
	before: string | null,
	/**  The service now (None: removed elsewhere). */
	after: string | null,
};

/**  What a listening process appears to be. */
export type ServiceKind = 
/**  Vite dev server. */
"vite" | 
/**  Next.js. */
"next" | 
/**  Astro. */
"astro" | 
/**  Nuxt. */
"nuxt" | 
/**  Remix / React Router. */
"remix" | 
/**  SvelteKit (a Vite project with `svelte.config.js`). */
"svelteKit" | 
/**  Angular CLI (`ng serve`). */
"angular" | 
/**  webpack-dev-server (webpack, Create React App, Vue CLI). */
"webpack" | 
/**  Django. */
"django" | 
/**  Flask. */
"flask" | 
/**  FastAPI. */
"fastApi" | 
/**  Ruby on Rails. */
"rails" | 
/**  Laravel (`artisan serve`). */
"laravel" | 
/**  Hugo. */
"hugo" | 
/**  Jekyll. */
"jekyll" | 
/**  Another Node.js / Bun / Deno server. */
"node" | 
/**  Python (Django, Flask, FastAPI/uvicorn, http.server…). */
"python" | 
/**  Ruby (Rails, Puma…). */
"ruby" | 
/**  PHP. */
"php" | 
/**  Java / JVM. */
"java" | 
/**  Go. */
"go" | 
/**  A port published by Docker, OrbStack or Colima. */
"docker" | 
/**  A database or cache (not HTTP). */
"database" | 
/**  A macOS system service, e.g. AirPlay Receiver on 5000/7000. */
"system" | 
/**  Anything else. */
"other";

/**  All preferences, with defaults applied. */
export type Settings = {
	/**  Appearance override. */
	theme: Theme,
	/**  Show the Teitunnel icon in the menu bar. */
	showInMenuBar: boolean,
	/**  Notify when this Mac's connector goes down, comes back or crash-loops. */
	notifyConnectors: boolean,
	/**  Notify when a Quick Share goes live or fails. */
	notifyQuickShares: boolean,
	/**  Notify when the Doctor finds a new error. */
	notifyDoctor: boolean,
	/**  Check for app updates by itself (at launch and daily). */
	checkForUpdates: boolean,
	/**
	 *  The one-time "Install teitunnel?" offer was answered (Install or Not now), on
	 *  installs where the CLI isn't put on the PATH by the installer (D-090).
	 */
	cliOfferDismissed: boolean,
	/**
	 *  Doctor issues the user chose to ignore (stable issue ids). Changed with
	 *  [`set_ignored`], not through a patch, so concurrent toggles can't lose one.
	 */
	ignoredIssues: string[],
};

/**  A partial update: only the fields that are set change. */
export type SettingsPatch = {
	/**  New appearance override. */
	theme?: Theme | null,
	/**  New menu bar visibility. */
	showInMenuBar?: boolean | null,
	/**  Connector notifications on or off. */
	notifyConnectors?: boolean | null,
	/**  Quick Share notifications on or off. */
	notifyQuickShares?: boolean | null,
	/**  Doctor notifications on or off. */
	notifyDoctor?: boolean | null,
	/**  Automatic update checks on or off. */
	checkForUpdates?: boolean | null,
	/**  The command line offer answered. */
	cliOfferDismissed?: boolean | null,
};

/**  How bad an issue is. */
export type Severity = 
/**  Something doesn't work. */
"error" | 
/**  Something may stop working, or needs attention. */
"warning" | 
/**  Worth knowing; nothing is broken. */
"info";

/**  Live traffic numbers for a share. */
export type ShareStats = {
	/**  Requests served. */
	requests: number,
	/**  Requests that failed. */
	errors: number,
};

/**  Where a share is in its life. */
export type ShareStatus = 
/**  cloudflared is starting and asking for a URL. */
{ status: "starting" } | 
/**  The URL works. */
{ status: "live" } | 
/**  Connection lost; cloudflared is reconnecting or restarting. */
{ status: "reconnecting" } | 
/**  It failed and won't recover by itself. */
{ status: "failed"; 
/**  What went wrong, for the user. */
message: Text };

/**  What a step does, for its icon. */
export type StepKind = 
/**  Create the tunnel. */
"createTunnel" | 
/**  Update the tunnel's routes. */
"putConfig" | 
/**  Add a DNS record. */
"createRecord" | 
/**  Repoint a DNS record. */
"updateRecord" | 
/**  Delete a DNS record. */
"deleteRecord" | 
/**  Stop this Mac's connector. */
"stopConnector" | 
/**  Delete the tunnel. */
"deleteTunnel" | 
/**  Add a login method. */
"loginMethod" | 
/**  Create, change or remove a route's login. */
"accessApp" | 
/**  Route or stop routing a private network. */
"networkRoute" | 
/**  Load balance a route, or stop. */
"loadBalancer" | 
/**  Check the route works. */
"verify";

/**  The state of one step while applying. */
export type StepState = 
/**  In progress. */
{ state: "running" } | 
/**  Finished. */
{ state: "done" } | 
/**  Not run by the executor (verification happens afterwards). */
{ state: "skipped" } | 
/**  Failed with a message. */
{ state: "failed"; 
/**  What went wrong. */
message: Text } | 
/**  Being undone after a later step failed. */
{ state: "undoing" } | 
/**  Undone. */
{ state: "undone" } | 
/**  Couldn't be undone; left in place. */
{ state: "undoFailed"; 
/**  What went wrong. */
message: Text };

/**  One step of a plan, as shown in the preview. */
export type StepView = {
	/**  What it does. */
	kind: StepKind,
	/**  One line for the user. */
	description: Text,
	/**  "Copy as command" text, when there's an equivalent command. */
	command: string | null,
};

/**
 *  A message for the user: a catalog key and its arguments.
 * 
 *  Also deserializes from a plain string, shown verbatim: that's how text stored
 *  before messages had keys (activity history) still loads.
 */
export type Text = {
	/**  The catalog key, e.g. `core.doctor.dnsMissing.title`. */
	key: string,
	/**  Values for the message's `{placeholders}`; `count` picks a plural form. */
	args: { [key in string]: Arg },
};

/**  Appearance override. */
export type Theme = 
/**  Follow the system appearance. */
"system" | 
/**  Always light. */
"light" | 
/**  Always dark. */
"dark";

/**  A page of Cloudflare's API token settings. */
export type TokenPage = 
/**  "Create API token" with Teitunnel's permissions pre-selected. */
"create" | 
/**  The list of tokens, to add permissions to an existing one. */
"edit";

/**  Live traffic of one tunnel's connector on this Mac. */
export type Traffic = {
	/**  Samples newer than the read's `since` (all of them without it), oldest first. */
	series: TrafficSeries,
	/**  Requests since the connector started. */
	totalRequests: number,
	/**  Failed requests since the connector started. */
	totalErrors: number,
	/**  Edge connections now. */
	connections: number,
	/**  Round-trip time to the edge now, in milliseconds. */
	rttMs: number | null,
	/**  Edge locations, e.g. `AMS`. */
	locations: string[],
};

/**  Samples as columns: entry `i` of every column belongs to the same interval. */
export type TrafficSeries = {
	/**  End of each interval, in milliseconds since the epoch; ascending. */
	at: number[],
	/**  Seconds each interval covers (rates are counts divided by this). */
	span: number[],
	/**  Requests during the interval. */
	requests: number[],
	/**  Failed requests (the origin couldn't be reached) during the interval. */
	errors: number[],
	/**  1xx and 2xx responses. */
	ok: number[],
	/**  3xx responses. */
	redirects: number[],
	/**  4xx responses. */
	clientErrors: number[],
	/**  5xx responses. */
	serverErrors: number[],
	/**  Most requests in flight at once (at the sample; the peak for rollups). */
	concurrent: number[],
	/**  Edge connections (at the sample; the lowest for rollups). */
	connections: number[],
	/**  Smoothed round trip to the edge, in milliseconds (the mean for rollups). */
	rttMs: (number | null)[],
};

/**  A tunnel in the account. */
export type TunnelSummary = {
	/**  Tunnel id. */
	id: string,
	/**  Name. */
	name: string,
	/**  Cloudflare's status: `inactive`, `degraded`, `healthy` or `down`. */
	status: string,
	/**  Created (RFC 3339). */
	createdAt: string,
	/**  Routes in its remote configuration (None: configured locally, or unreadable). */
	routes: number | null,
	/**  Machines running it. */
	connectors: ConnectorView[],
	/**  One of this Mac's tunnels (created and run by Teitunnel here). */
	thisMac: boolean,
	/**  This Mac's default tunnel (where new routes go unless another is chosen). */
	isDefault: boolean,
	/**  Connector state on this Mac, for this Mac's tunnel. */
	connector: ConnectorState | null,
};

/**  This Mac's tunnel. */
export type TunnelView = {
	/**  Tunnel id. */
	id: string,
	/**  Name. */
	name: string,
	/**  Connector state on this Mac (`None`: not running). */
	connector: ConnectorState | null,
	/**  The machine tunnel: where routes go unless another is chosen. */
	isDefault: boolean,
};

/**  Whether a newer cloudflared is available. */
export type UpdateInfo = {
	/**  Latest published version. */
	latest: string,
	/**  Whether it's newer than the one in use (or none is installed). */
	available: boolean,
};

/**  Where an update stands. */
export type UpdateState = 
/**  Nothing checked yet. */
{ state: "idle" } | 
/**  Asking whether there's a newer version. */
{ state: "checking" } | 
/**  This is the latest version. */
{ state: "upToDate" } | 
/**  Downloading a newer version. */
{ state: "downloading"; 
/**  The version being downloaded. */
version: string; 
/**  Share downloaded, 0–1, when the size is known. */
progress: number | null } | 
/**  Downloaded and verified; installs on restart (or on quit, see `install_on_quit`). */
{ state: "ready"; 
/**  The new version. */
version: string; 
/**  Its release notes (Markdown). */
notes: string | null } | 
/**  Checking or downloading failed; the next check tries again. */
{ state: "failed"; 
/**  Why. */
message: Text };

/**  What the app shows about updates. */
export type UpdateStatus = {
	/**  The running version. */
	currentVersion: string,
	/**  Why this copy can't update itself, if it can't (checks are off then). */
	unsupported: Text | null,
	/**  Automatic checks are on. */
	automatic: boolean,
	/**  When the last check finished (Unix ms). */
	lastChecked: number | null,
	/**  Where an update stands. */
	state: UpdateState,
	/**  A ready update installs when the app quits. */
	installOnQuit: boolean,
};

/**  The result of checking one hostname. */
export type Verification = {
	/**  Hostname. */
	hostname: string,
	/**  The origin's HTTP status, when it answered. */
	status: number | null,
	/**  What's wrong, if anything. */
	failure: Failure | null,
	/**  The failure, in a sentence for the UI. */
	message: Text | null,
	/**
	 *  Cloudflare asked for a login (Access) instead of passing the request on, so the
	 *  check reached the edge but not the origin behind the login.
	 */
	protected: boolean,
	/**
	 *  The origin answered with a Server-Sent Events stream (Quick Shares don't carry
	 *  them).
	 */
	eventStream: boolean,
};

/**  Something the user should know before applying. */
export type Warning = 
/**  Only one tunnel serves the hostname: there's nothing to fail over to yet. */
{ type: "singleEndpoint"; 
/**  Hostname. */
hostname: string } | 
/**  A record Teitunnel didn't create will be replaced. */
{ type: "replacesForeignRecord"; 
/**  Hostname. */
hostname: string; 
/**  Existing type. */
kind: string; 
/**  Existing content. */
content: string } | 
/**  A record Teitunnel didn't create will be deleted. */
{ type: "deletesForeignRecord"; 
/**  Hostname. */
hostname: string; 
/**  Type. */
kind: string; 
/**  Content. */
content: string } | 
/**  A record Teitunnel didn't create is left in place. */
{ type: "keepsForeignRecord"; 
/**  Hostname. */
hostname: string } | 
/**  No routes are left on the tunnel. */
{ type: "tunnelEmpty" } | 
/**  The origin isn't on this Mac, so it must be reachable from here. */
{ type: "remoteOrigin"; 
/**  The origin. */
origin: string } | 
/**
 *  The range isn't private address space: WARP clients would send traffic for those
 *  public addresses to this Mac instead of the internet.
 */
{ type: "publicNetwork"; 
/**  The range. */
network: string } | 
/**
 *  Part of the range is already routed to another tunnel; the more specific route
 *  wins for the addresses both cover.
 */
{ type: "overlapsNetwork"; 
/**  The range being added. */
network: string; 
/**  The other route's range. */
other: string; 
/**  The other route's tunnel. */
tunnel: string };

/**  DNS permission for one domain. */
export type ZoneGrant = {
	/**  Zone id. */
	zoneId: string,
	/**  Domain name. */
	zoneName: string,
	/**  Whether DNS records can be edited. */
	dnsEdit: Grant,
};

/**  A zone the account can use. */
export type ZoneRef = {
	/**  Zone id. */
	id: string,
	/**  Apex name. */
	name: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

