// Generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Regenerate with `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app version, platform and data directory. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Called by a webview once its first frame is painted; shows its window. */
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	/**  The system accent colour as `#rrggbb`, or `null` to keep the stylesheet default. */
	appAccentColor: () => __TAURI_INVOKE<string | null>("app_accent_color"),
	/**  Records an uncaught webview error in the app log (redacted like every other line). */
	appReportError: (message: string, stack: string | null) => __TAURI_INVOKE<void>("app_report_error", { message, stack }),
	/**  Opens the Settings window (same as ⌘,). */
	appOpenSettings: () => __TAURI_INVOKE<null>("app_open_settings"),
	/**
	 *  Quits after the user confirmed. With `keep_running`, this Mac's connectors switch to
	 *  Always-on first (so routes stay up); if that fails, the app stays open.
	 */
	appQuit: (keepRunning: boolean) => __TAURI_INVOKE<null>("app_quit", { keepRunning }),
	/**  Whether Teitunnel opens at login (hidden, in the menu bar). */
	appOpenAtLogin: () => __TAURI_INVOKE<boolean>("app_open_at_login"),
	/**  Turns opening at login on or off. */
	appSetOpenAtLogin: (enabled: boolean) => __TAURI_INVOKE<null>("app_set_open_at_login", { enabled }),
	/**  Returns all settings, with defaults applied. */
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	/**  Updates the given settings and returns the result. Every window is notified. */
	settingsSet: (patch: SettingsPatch) => __TAURI_INVOKE<Settings>("settings_set", { patch }),
	/**  The cloudflared binary in use, or `null` if none is installed. */
	binaryStatus: () => __TAURI_INVOKE<{
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
} | null>("binary_status"),
	/**  Downloads, verifies and installs the latest cloudflared into the app data folder. */
	binaryInstall: (onProgress: Channel<InstallProgress>) => __TAURI_INVOKE<BinaryInfo>("binary_install", { onProgress }),
	/**  Checks Cloudflare's releases for a newer cloudflared. */
	binaryCheckUpdate: () => __TAURI_INVOKE<UpdateInfo>("binary_check_update"),
	/**  Shows the binary in Finder. */
	binaryReveal: () => __TAURI_INVOKE<null>("binary_reveal"),
	/**  Services listening on this Mac and Docker containers' ports, likely dev servers first. */
	servicesList: () => __TAURI_INVOKE<LocalService[]>("services_list"),
	/**  Starts sharing `origin`. The URL arrives via `EntityChanged` for `quickShares`. */
	quickShareStart: (origin: string, stopAfterMinutes: number | null) => __TAURI_INVOKE<QuickShare>("quick_share_start", { origin, stopAfterMinutes }),
	/**  Stops a share. */
	quickShareStop: (id: string) => __TAURI_INVOKE<null>("quick_share_stop", { id }),
	/**  Running shares, newest first. */
	quickShareList: () => __TAURI_INVOKE<QuickShare[]>("quick_share_list"),
	/**  Request counts for a share (polled by the UI while visible). */
	quickShareStats: (id: string) => __TAURI_INVOKE<ShareStats>("quick_share_stats", { id }),
	/**  The newest cloudflared log lines of a share. */
	quickShareLogs: (id: string, limit: number) => __TAURI_INVOKE<LogLine[]>("quick_share_logs", { id, limit }),
	/**  An SVG QR code for `url` (dark modules use `currentColor`). */
	quickShareQr: (url: string) => __TAURI_INVOKE<string>("quick_share_qr", { url }),
	/**  Connected accounts. */
	accountsList: () => __TAURI_INVOKE<Account[]>("accounts_list"),
	/**
	 *  Verifies an API token and connects every account it reaches. The token is stored in
	 *  the keychain and never sent back.
	 */
	accountsAddToken: (token: string) => __TAURI_INVOKE<Account[]>("accounts_add_token", { token }),
	/**  Opens Cloudflare's "Create API token" page with Teitunnel's permissions pre-selected. */
	accountsOpenTokenPage: () => __TAURI_INVOKE<null>("accounts_open_token_page"),
	/**  Whether `~/.cloudflared/cert.pem` (from `cloudflared tunnel login`) exists. */
	accountsDetectCert: () => __TAURI_INVOKE<boolean>("accounts_detect_cert"),
	/**  Imports the login from `~/.cloudflared/cert.pem` (the file is only read). */
	accountsImportCert: () => __TAURI_INVOKE<Account>("accounts_import_cert"),
	/**  Disconnects an account and deletes its credentials from the keychain. */
	accountsRemove: (id: string) => __TAURI_INVOKE<null>("accounts_remove", { id }),
	/**  What the account's credential can do. */
	accountsCapabilities: (id: string) => __TAURI_INVOKE<Capabilities>("accounts_capabilities", { id }),
	/**  Domains in an account. */
	domainsList: (accountId: string) => __TAURI_INVOKE<Domain[]>("domains_list", { accountId }),
	/**  Whether "Sign in with Cloudflare" (OAuth) is available in this build. */
	accountsOauthAvailable: () => __TAURI_INVOKE<boolean>("accounts_oauth_available"),
	/**
	 *  Signs in with Cloudflare in the browser. The authorize URL is sent on `on_url` (for
	 *  "Copy link" if the browser didn't open); resolves when the browser comes back.
	 */
	accountsOauthSignIn: (onUrl: Channel<string>) => __TAURI_INVOKE<Account[]>("accounts_oauth_sign_in", { onUrl }),
	/**  Cancels a sign-in that's waiting for the browser. */
	accountsOauthCancel: () => __TAURI_INVOKE<void>("accounts_oauth_cancel"),
	/**  This Mac's tunnel and routes in an account. */
	routesOverview: (accountId: string) => __TAURI_INVOKE<RoutesOverview>("routes_overview", { accountId }),
	/**  Plans a change for review. Nothing is changed. */
	routesPreview: (accountId: string, change: Change) => __TAURI_INVOKE<PlanView>("routes_preview", { accountId, change }),
	/**
	 *  Applies a reviewed change. Step progress streams on `on_progress`. Fails with
	 *  `conflict` if anything changed since the preview (preview again).
	 */
	routesApply: (accountId: string, change: Change, fingerprint: string, confirmed: boolean, onProgress: Channel<Progress>) => __TAURI_INVOKE<Outcome>("routes_apply", { accountId, change, fingerprint, confirmed, onProgress }),
	/**
	 *  Checks a route end to end. With `wait`, transient failures (connector connecting,
	 *  propagation) are retried for up to 30 s, as right after applying.
	 */
	routesVerify: (accountId: string, hostname: string, wait: boolean) => __TAURI_INVOKE<Verification>("routes_verify", { accountId, hostname, wait }),
	/**  An outside edit of this Mac's routes, if there is one. */
	routesDrift: (accountId: string) => __TAURI_INVOKE<{
	/**  Tunnel id. */
	tunnelId: string,
	/**  Version Teitunnel last wrote. */
	appliedVersion: number,
	/**  Version now. */
	currentVersion: number,
	/**  Routes that differ. */
	changes: RuleChange[],
} | null>("routes_drift", { accountId }),
	/**  Accepts an outside edit as the new baseline ("Keep theirs"). */
	routesKeepTheirs: (accountId: string) => __TAURI_INVOKE<null>("routes_keep_theirs", { accountId }),
	/**  Recent changes in an account, newest first. */
	routesActivity: (accountId: string) => __TAURI_INVOKE<ActivityEntry[]>("routes_activity", { accountId }),
	/**  Every tunnel in the account, this Mac's first. */
	tunnelsList: (accountId: string) => __TAURI_INVOKE<TunnelSummary[]>("tunnels_list", { accountId }),
	/**  Starts this Mac's connector for the account's tunnel. */
	tunnelsStart: (accountId: string) => __TAURI_INVOKE<null>("tunnels_start", { accountId }),
	/**  Stops this Mac's connector for a tunnel. Its routes stop answering until it starts. */
	tunnelsStop: (accountId: string, tunnelId: string) => __TAURI_INVOKE<null>("tunnels_stop", { accountId, tunnelId }),
	/**  Removes a tunnel's stale connections (left by connectors that went away uncleanly). */
	tunnelsClean: (accountId: string, tunnelId: string) => __TAURI_INVOKE<null>("tunnels_clean", { accountId, tunnelId }),
	/**
	 *  cloudflared configurations found on this Mac (`~/.cloudflared/config.yml`, …). Only
	 *  reads; credentials' secrets are never read.
	 */
	importScan: () => __TAURI_INVOKE<LocalSetup[]>("import_scan"),
	/**  cloudflared processes on this Mac that Teitunnel didn't start. */
	foreignList: () => __TAURI_INVOKE<ForeignConnector[]>("foreign_list"),
	/**  Stops a cloudflared process Teitunnel didn't start (after re-checking it's one). */
	foreignStop: (pid: number) => __TAURI_INVOKE<null>("foreign_stop", { pid }),
	/**  The newest log lines of this Mac's connector for a tunnel. */
	tunnelsLogs: (tunnelId: string, limit: number) => __TAURI_INVOKE<LogLine[]>("tunnels_logs", { tunnelId, limit }),
	/**  The last hour of this Mac's connector traffic for a tunnel. */
	tunnelsTraffic: (tunnelId: string) => __TAURI_INVOKE<{
	/**  The last hour, oldest first. */
	points: TrafficPoint[],
	/**  Requests since the connector started. */
	totalRequests: number,
	/**  Failed requests since the connector started. */
	totalErrors: number,
	/**  Edge connections now. */
	connections: number,
	/**  Round-trip time to the edge, in milliseconds. */
	rttMs: number | null,
	/**  Edge locations, e.g. `AMS`. */
	locations: string[],
} | null>("tunnels_traffic", { tunnelId }),
	/**  Whether this Mac's connector for the account keeps running when Teitunnel quits. */
	tunnelsAlwaysOn: (accountId: string) => __TAURI_INVOKE<AlwaysOn>("tunnels_always_on", { accountId }),
	/**
	 *  Switches this Mac's connector between running with the app and running as a
	 *  service (keeps running after quit and at login), without a gap.
	 */
	tunnelsSetAlwaysOn: (accountId: string, enabled: boolean) => __TAURI_INVOKE<null>("tunnels_set_always_on", { accountId, enabled }),
	/**  Checks cloudflared and every connected account; issues sorted by severity. */
	doctorRun: () => __TAURI_INVOKE<Issue[]>("doctor_run"),
	/**
	 *  Applies every fix that needs no review (owned DNS repairs and orphan cleanup), each
	 *  through a fresh plan; the rest are left for the user.
	 */
	doctorFixSafe: () => __TAURI_INVOKE<FixReport>("doctor_fix_safe"),
	/**  What a diagnostics export would contain (shown before saving). */
	diagnosticsPreview: () => __TAURI_INVOKE<FileSummary[]>("diagnostics_preview"),
	/**  Saves the diagnostics bundle to Downloads and shows it in Finder. Returns its path. */
	diagnosticsExport: () => __TAURI_INVOKE<string>("diagnostics_export"),
};

/** Events */
export const events = {
	entityChanged: makeEvent<EntityChanged>("entity-changed"),
	menuAction: makeEvent<MenuAction>("menu-action"),
};

/* Types */
/**  A connected Cloudflare account. */
export type Account = {
	/**  Cloudflare account id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  How it was connected. */
	credential: CredentialKind,
	/**  For cert.pem credentials: the only zone the credential works for. */
	limitedZone: string | null,
};

/**  One entry of the activity log. */
export type ActivityEntry = {
	/**  Row id. */
	id: number,
	/**  Milliseconds since the epoch. */
	at: number | null,
	/**  What was asked, e.g. "Add app.xyz.com → http://localhost:3000". */
	summary: string,
	/**  `applied`, `rolledBack` or `partiallyApplied`. */
	outcome: string,
	/**  Step descriptions and any error, as shown in the inspector. */
	detail: string[],
};

/**  Whether this Mac's connector can run as a service, and whether it does. */
export type AlwaysOn = {
	/**  This system supports Always-on. */
	supported: boolean,
	/**  The connector runs as a service. */
	enabled: boolean,
};

/**  An error as shown to the user: what happened, and what to do about it. */
export type AppError = {
	/**  Category for programmatic handling. */
	code: ErrorCode,
	/**  One sentence describing what happened. */
	message: string,
	/**  What the user can do about it. */
	hint: string | null,
	/**  The input field the error refers to. */
	field: string | null,
};

/**  Static facts about the running app. */
export type AppInfo = {
	/**  App version (semver). */
	version: string,
	/**  Operating system: `macos`, `linux` or `windows`. */
	platform: string,
	/**  CPU architecture, e.g. `aarch64`. */
	arch: string,
	/**  Directory holding the database, logs and managed binaries. */
	dataDir: string,
};

/**  Where cloudflared comes from and whether it's new enough. */
export type BinaryInfo = {
	/**  Absolute path. */
	path: string,
	/**  `managed`, `system` or `override`. */
	source: string,
	/**  Version, if readable. */
	version: string | null,
	/**  Whether it supports everything Teitunnel needs. */
	supported: boolean,
};

/**  Everything a credential can do in one account. */
export type Capabilities = {
	/**  List domains. */
	zonesRead: Grant,
	/**  List tunnels. */
	tunnelsRead: Grant,
	/**  Create and configure tunnels. */
	tunnelsEdit: Grant,
	/**  Access policies (optional feature). */
	accessEdit: Grant,
	/**  DNS editing, per domain. */
	zones: ZoneGrant[],
};

/**  A change the user asks for (or a Doctor fix proposes). */
export type Change = 
/**  Add a route. */
{ type: "addRoute"; 
/**  The route. */
route: RouteInput } | 
/**  Edit or rename a route. */
{ type: "updateRoute"; 
/**  Current hostname. */
hostname: string; 
/**  Current path. */
path: string | null; 
/**  The new definition. */
route: RouteInput } | 
/**  Remove a route. */
{ type: "removeRoute"; 
/**  Hostname. */
hostname: string; 
/**  Path. */
path: string | null } | 
/**  Remove every route and delete this Mac's tunnel. */
{ type: "removeTunnel" } | 
/**  Undo an outside edit of this Mac's routes. */
{ type: "restoreConfig" } | 
/**  Add several routes at once (import from an existing cloudflared setup). */
{ type: "importRoutes"; 
/**  The routes. */
routes: RouteInput[] } | 
/**  Delete one DNS record (an orphan found by the Doctor). */
{ type: "deleteRecord"; 
/**  Zone id. */
zoneId: string; 
/**  The record's name. */
hostname: string; 
/**  Record id. */
recordId: string };

/**  One connector connected to the edge. */
export type ConnectionView = {
	/**  Edge location, e.g. `ams01`. */
	colo: string,
	/**  cloudflared version. */
	version: string,
	/**  Public IP it connects from. */
	originIp: string,
	/**  When it connected (RFC 3339). */
	openedAt: string,
};

/**  Lifecycle of one connector (ARCHITECTURE §5.1). */
export type ConnectorState = 
/**  Not running. */
{ state: "stopped" } | 
/**  The process is being spawned. */
{ state: "starting" } | 
/**  Running, but no edge connection yet. */
{ state: "connecting" } | 
/**  Serving traffic. */
{ state: "healthy"; 
/**  Registered edge connections. */
connections: number } | 
/**
 *  Running with no edge connections after having had some (or after the start
 *  timeout).
 */
{ state: "degraded" } | 
/**  Exited unexpectedly; restarts after a backoff. */
{ state: "crashed"; 
/**  Restart attempt number (1-based). */
attempt: number; 
/**  Milliseconds until the restart. */
retry_in_ms: number; 
/**  Exit code, when there was one. */
exit_code: number | null } | 
/**  Crashed too often in a short time; not restarted automatically. */
{ state: "crashLoop"; 
/**  Exit code of the last crash. */
exit_code: number | null } | 
/**  Shutting down. */
{ state: "stopping" };

/**  How an account was connected. */
export type CredentialKind = 
/**  A user API token. */
"apiToken" | 
/**  OAuth sign-in (refresh token in the keychain). */
"oauth" | 
/**  Imported from `cloudflared tunnel login` (cert.pem); one zone only. */
"certPem";

/**  Whether a route's DNS record points at this Mac's tunnel. */
export type DnsState = 
/**  A proxied CNAME to the tunnel. */
{ state: "ok" } | 
/**  No record. */
{ state: "missing" } | 
/**  A record pointing somewhere else (or not proxied). */
{ state: "elsewhere"; 
/**  What it points at. */
content: string };

/**  A domain in a connected account. */
export type Domain = {
	/**  Zone id. */
	id: string,
	/**  Domain name. */
	name: string,
	/**  Setup state. */
	status: DomainStatus,
	/**  Cloudflare nameservers to set at the registrar. */
	nameServers: string[],
	/**  Nameservers currently at the registrar (before the switch). */
	originalNameServers: string[],
	/**  Plan name. */
	plan: string | null,
	/**  Whether the proxy is paused. */
	paused: boolean,
};

/**  Where a domain is in its setup. */
export type DomainStatus = 
/**  Active on Cloudflare: routes can use it. */
"active" | 
/**  Waiting for the registrar to switch nameservers. */
"pending" | 
/**  Nameservers moved away from Cloudflare. */
"moved" | 
/**  Being set up, or a state we don't know. */
"other";

/**  An outside edit of this Mac's tunnel configuration. */
export type Drift = {
	/**  Tunnel id. */
	tunnelId: string,
	/**  Version Teitunnel last wrote. */
	appliedVersion: number,
	/**  Version now. */
	currentVersion: number,
	/**  Routes that differ. */
	changes: RuleChange[],
};

/**  Emitted after anything changes, so the UI can invalidate the affected queries. */
export type EntityChanged = {
	/**  What kind of entity changed. */
	kind: EntityKind,
	/**  Which one, when a single entity changed. */
	id: string | null,
};

/**  Kinds of entities the UI caches. Each maps to TanStack Query keys on the frontend. */
export type EntityKind = 
/**  App settings. */
"settings" | 
/**  Quick Shares (list, status, URL). */
"quickShares" | 
/**  Connected Cloudflare accounts (and their domains). */
"accounts" | 
/**  Routes and this Mac's tunnel (id: the account). */
"routes";

/**  Machine-readable error category. The frontend branches on this, never on `message`. */
export type ErrorCode = 
/**  An unexpected failure. The message is safe to show; details are in the app log. */
"internal" | 
/**  The input was rejected; `field` names the offending field. */
"invalidInput" | 
/**  The thing acted on doesn't exist (any more). */
"notFound" | 
/**  cloudflared isn't installed. */
"cloudflaredMissing" | 
/**  Busy or exhausted; retrying later may work. */
"unavailable" | 
/**
 *  Something changed since the user looked, or a confirmation is missing: refresh
 *  the preview.
 */
"conflict" | 
/**  The Cloudflare credential lacks a permission. */
"permissionDenied";

/**  Why a route doesn't work. */
export type Failure = 
/**  There's no DNS record for the hostname. */
{ type: "noRecord" } | 
/**  The record exists but doesn't point at this Mac's tunnel (or isn't proxied). */
{ type: "recordElsewhere"; 
/**  What it points at. */
content: string } | 
/**  The edge couldn't be reached (network, firewall). */
{ type: "edgeUnreachable"; 
/**  The error. */
message: string } | 
/**  The certificate doesn't cover the hostname (Universal SSL covers one level). */
{ type: "certificateNotCovered" } | 
/**  Cloudflare doesn't know the hostname yet (error 1001), usually propagation. */
{ type: "notOnCloudflareYet" } | 
/**  No connector is connected to the tunnel (error 1033). */
{ type: "noConnector" } | 
/**  The record points at a tunnel that doesn't serve it (error 1016 / 530). */
{ type: "tunnelMismatch" } | 
/**  The connector couldn't reach the origin (502). */
{ type: "originUnreachable"; 
/**  Whether something listens on the origin's local port (None: not local). */
listening: boolean | null } | 
/**  The origin didn't answer in time (504). */
{ type: "originTimeout" };

/**  What the preview shows for a file. */
export type FileSummary = {
	/**  Path inside the archive. */
	name: string,
	/**  Size in bytes. */
	size: number,
	/**  The first lines, for a quick look. */
	excerpt: string,
};

/**  A way to fix an issue. */
export type Fix = 
/**  A change in Cloudflare, previewed as a plan before it's applied. */
{ type: "change"; 
/**  Button title, e.g. "Fix the DNS Record". */
label: string; 
/**  The change. */
change: Change } | 
/**  Install (or update) the managed cloudflared. */
{ type: "installBinary" } | 
/**  Start this Mac's connector. */
{ type: "startConnector"; 
/**  Account. */
accountId: string } | 
/**  Accept an outside edit of this Mac's routes. */
{ type: "keepTheirs"; 
/**  Account. */
accountId: string } | 
/**  Create a token with the right permissions. */
{ type: "reconnect" } | 
/**  Remove a tunnel's stale connections. */
{ type: "cleanConnections"; 
/**  Account. */
accountId: string; 
/**  Tunnel. */
tunnelId: string };

/**  What "Fix all safe issues" did. */
export type FixReport = {
	/**  Issues fixed. */
	fixed: number,
	/**  Issues left for the user (their fix needs a confirmation or a decision). */
	skipped: number,
	/**  Fixes that failed (and were rolled back), with why. */
	failed: string[],
};

/**  A cloudflared process Teitunnel doesn't manage. */
export type ForeignConnector = {
	/**  Process id. */
	pid: number,
	/**  The command line, with tokens replaced by `[redacted]`. */
	command: string,
	/**  What it's doing. */
	mode: ForeignMode,
	/**  Started by launchd (a service) rather than a terminal. */
	service: boolean,
	/**  Its metrics address, when it has one. */
	metrics: string | null,
	/**  Edge connections reported by `/ready` (None: no metrics server answered). */
	connections: number | null,
};

/**  What a foreign cloudflared is doing. */
export type ForeignMode = 
/**  `tunnel --url …`: a Quick Tunnel. */
{ type: "quickTunnel"; 
/**  The local origin. */
origin: string } | 
/**  `tunnel run [name]`, with a token or a config. */
{ type: "named"; 
/**  The tunnel name or id, when given on the command line. */
tunnel: string | null; 
/**  The config file, when given. */
config: string | null } | 
/**  Something else (`access`, `proxy-dns`, …). */
{ type: "other" };

/**  One route found in a config file. */
export type FoundRoute = {
	/**  Hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Service, e.g. `http://localhost:3000`. */
	service: string,
	/**  Why it can't be imported, if it can't. */
	unsupported: string | null,
};

/**  The result of probing one permission. */
export type Grant = 
/**  Allowed. */
"yes" | 
/**  Not allowed. */
"no" | 
/**  Couldn't be checked right now. */
"unknown";

/**  Install progress, streamed to the webview. */
export type InstallProgress = 
/**  Downloading: bytes received of total. */
{ step: "downloading"; 
/**  Bytes received. */
received: number; 
/**  Total bytes. */
total: number } | 
/**  Checking checksums and the code signature. */
{ step: "verifying" } | 
/**  Moving the binary into place. */
{ step: "installing" };

/**  A detected problem. */
export type Issue = {
	/**  Stable id (check, account, subject), so "Ignore" survives restarts. */
	id: string,
	/**  Which check found it, e.g. `dns.missing`. */
	check: string,
	/**  How bad it is. */
	severity: Severity,
	/**  The account it's in, if any. */
	accountId: string | null,
	/**  What it's about, e.g. a hostname or a tunnel name. */
	subject: string,
	/**  One line. */
	title: string,
	/**  What it means and what to do. */
	detail: string,
	/**  Supporting facts (records, states). */
	evidence: string[],
	/**  Fixes, the recommended one first. */
	fixes: Fix[],
};

/**  A TCP port something on this machine is listening on. */
export type LocalService = {
	/**  The port. */
	port: number,
	/**  Whether it listens on all interfaces (vs. loopback only). */
	allInterfaces: boolean,
	/**  Owning process id. */
	pid: number,
	/**  Process name, e.g. `node`. */
	process: string,
	/**  What it looks like, e.g. a Vite dev server. */
	kind: ServiceKind,
	/**  Project the process runs in (from its working directory), e.g. `my-app`. */
	project: string | null,
	/**  Suggested origin URL, e.g. `http://localhost:5173`. */
	origin: string,
};

/**  A cloudflared configuration found on disk. */
export type LocalSetup = {
	/**  The config file. */
	configPath: string,
	/**  `tunnel:` (a UUID or a name). */
	tunnel: string | null,
	/**  The Cloudflare account the credentials belong to. */
	accountId: string | null,
	/**  The tunnel id from the credentials file. */
	tunnelId: string | null,
	/**  Routes (hostname rules) in order. */
	routes: FoundRoute[],
	/**
	 *  Settings that apply to every route (`originRequest`), which Teitunnel can't
	 *  carry over per route yet.
	 */
	hasGlobalOptions: boolean,
	/**  Problems reading the file. */
	problem: string | null,
};

/**  One cloudflared log line, for the log drawer. */
export type LogLine = {
	/**  Timestamp as printed by cloudflared. */
	time: string | null,
	/**  `debug`, `info`, `warn`, `error`, `fatal` or `raw`. */
	level: string,
	/**  The message. */
	message: string,
	/**  The `error` field, if any. */
	error: string | null,
};

/**  Emitted when a menu-bar item that the webview handles is chosen. */
export type MenuAction = {
	/**  The chosen command. */
	command: MenuCommand,
};

/**  A menu-bar command the webview handles (navigation, panes, palette). */
export type MenuCommand = 
/**  File ▸ New Route (⌘N). */
"newRoute" | 
/**  File ▸ New Quick Share (⇧⌘N). */
"newQuickShare" | 
/**  View ▸ Toggle Sidebar (⌥⌘S). */
"toggleSidebar" | 
/**  View ▸ Toggle Inspector (⌥⌘I). */
"toggleInspector" | 
/**  View ▸ Refresh (⌘R). */
"refresh" | 
/**  View ▸ Command Palette (⌘K). */
"commandPalette" | 
/**  View ▸ Overview (⌘1). */
"goOverview" | 
/**  View ▸ Routes (⌘2). */
"goRoutes" | 
/**  View ▸ Quick Share (⌘3). */
"goQuickShare" | 
/**  View ▸ Domains (⌘4). */
"goDomains" | 
/**  View ▸ Tunnels (⌘5). */
"goTunnels" | 
/**  View ▸ Activity (⌘6). */
"goActivity" | 
/**  View ▸ Doctor (⌘7). */
"goDoctor" | 
/**  Quit was chosen while routes run through the app: ask what to do. */
"confirmQuit";

/**
 *  An HTTP(S) origin cloudflared can proxy to, e.g. `http://localhost:3000`.
 * 
 *  Parsing is forgiving about what people type: `3000`, `:3000`, `localhost:3000`,
 *  `127.0.0.1:8080` and full URLs all work. Paths and query strings are dropped;
 *  cloudflared proxies the whole host.
 */
export type OriginUrl = string;

/**  How applying ended. */
export type Outcome = 
/**  Every step succeeded. */
{ type: "applied"; 
/**  This Mac's tunnel afterwards (None once deleted). */
tunnelId: string | null; 
/**  Hostnames to verify next. */
verify: string[]; 
/**  The connector couldn't be started (the routes are configured, though). */
connectorError: string | null } | 
/**  A step failed and everything done before it was undone. */
{ type: "rolledBack"; 
/**  Index of the failed step. */
failedStep: number; 
/**  Why it failed. */
error: string } | 
/**  A step failed and some earlier changes couldn't be undone. */
{ type: "partiallyApplied"; 
/**  Index of the failed step. */
failedStep: number; 
/**  Why it failed. */
error: string; 
/**  What was left in place. */
leftovers: string[] };

/**  A plan, as shown in the preview. */
export type PlanView = {
	/**  Steps in order (empty: nothing to change). */
	steps: StepView[],
	/**  Things to review. */
	warnings: Warning[],
	/**  Confirmation needed (touches records Teitunnel didn't create). */
	requiresConfirmation: boolean,
	/**  Pass back to apply, so a change made meanwhile is caught. */
	fingerprint: string,
};

/**  A progress update for the step at `step` (index into the plan). */
export type Progress = {
	/**  Step index. */
	step: number,
	/**  Its state. */
	state: StepState,
};

/**  A running Quick Share, as the UI sees it. */
export type QuickShare = {
	/**  Identifier. */
	id: string,
	/**  The local service being shared. */
	origin: OriginUrl,
	/**  The public URL, once cloudflared has one. */
	url: string | null,
	/**  Current status. */
	status: ShareStatus,
	/**
	 *  Start time, milliseconds since the Unix epoch.
	 * 
	 *  Exported to TypeScript as `number` (values stay far below 2^53). The `u32` is
	 *  only a type hint for specta, which exports `u64` as bigint and `f64` as nullable.
	 */
	startedAt: number,
	/**  When it stops by itself, milliseconds since the Unix epoch. */
	stopAt: number | null,
};

/**  A route as typed in the add/edit sheet. */
export type RouteInput = {
	/**  Public hostname, e.g. `app.example.com`. */
	hostname: string,
	/**  Optional path regex, e.g. `^/api`. */
	path: string | null,
	/**  Origin, e.g. `3000` or `http://localhost:3000`. */
	origin: string,
};

/**  One route of this Mac's tunnel. */
export type RouteView = {
	/**  Public hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  Where traffic goes. */
	origin: string,
	/**  Whether the origin is on this Mac. */
	local: boolean,
	/**  The zone (domain) it belongs to. */
	zone: string | null,
	/**  Its DNS record. */
	dns: DnsState,
};

/**  Everything the Routes view shows for an account. */
export type RoutesOverview = {
	/**  This Mac's tunnel, if it has one. */
	tunnel: TunnelView | null,
	/**  Routes, sorted by domain then hostname. */
	routes: RouteView[],
	/**  Domains routes can use. */
	zones: ZoneRef[],
};

/**  One route that differs between what Teitunnel wrote and what's there now. */
export type RuleChange = {
	/**  Hostname. */
	hostname: string,
	/**  Path regex. */
	path: string | null,
	/**  The service Teitunnel wrote (None: added elsewhere). */
	before: string | null,
	/**  The service now (None: removed elsewhere). */
	after: string | null,
};

/**  What a listening process appears to be. */
export type ServiceKind = 
/**  Vite dev server. */
"vite" | 
/**  Next.js. */
"next" | 
/**  Astro. */
"astro" | 
/**  Nuxt. */
"nuxt" | 
/**  Remix / React Router. */
"remix" | 
/**  Django. */
"django" | 
/**  Flask. */
"flask" | 
/**  FastAPI. */
"fastApi" | 
/**  Ruby on Rails. */
"rails" | 
/**  Laravel (`artisan serve`). */
"laravel" | 
/**  Hugo. */
"hugo" | 
/**  Jekyll. */
"jekyll" | 
/**  Another Node.js / Bun / Deno server. */
"node" | 
/**  Python (Django, Flask, FastAPI/uvicorn, http.server…). */
"python" | 
/**  Ruby (Rails, Puma…). */
"ruby" | 
/**  PHP. */
"php" | 
/**  Java / JVM. */
"java" | 
/**  Go. */
"go" | 
/**  A port published by Docker, OrbStack or Colima. */
"docker" | 
/**  A database or cache (not HTTP). */
"database" | 
/**  A macOS system service, e.g. AirPlay Receiver on 5000/7000. */
"system" | 
/**  Anything else. */
"other";

/**  All preferences, with defaults applied. */
export type Settings = {
	/**  Appearance override. */
	theme: Theme,
	/**  Show the Teitunnel icon in the menu bar. */
	showInMenuBar: boolean,
};

/**  A partial update: only the fields that are set change. */
export type SettingsPatch = {
	/**  New appearance override. */
	theme?: Theme | null,
	/**  New menu bar visibility. */
	showInMenuBar?: boolean | null,
};

/**  How bad an issue is. */
export type Severity = 
/**  Something doesn't work. */
"error" | 
/**  Something may stop working, or needs attention. */
"warning" | 
/**  Worth knowing; nothing is broken. */
"info";

/**  Live traffic numbers for a share. */
export type ShareStats = {
	/**  Requests served. */
	requests: number,
	/**  Requests that failed. */
	errors: number,
};

/**  Where a share is in its life. */
export type ShareStatus = 
/**  cloudflared is starting and asking for a URL. */
{ status: "starting" } | 
/**  The URL works. */
{ status: "live" } | 
/**  Connection lost; cloudflared is reconnecting or restarting. */
{ status: "reconnecting" } | 
/**  It failed and won't recover by itself. */
{ status: "failed"; 
/**  What went wrong, for the user. */
message: string };

/**  What a step does, for its icon. */
export type StepKind = 
/**  Create the tunnel. */
"createTunnel" | 
/**  Update the tunnel's routes. */
"putConfig" | 
/**  Add a DNS record. */
"createRecord" | 
/**  Repoint a DNS record. */
"updateRecord" | 
/**  Delete a DNS record. */
"deleteRecord" | 
/**  Stop this Mac's connector. */
"stopConnector" | 
/**  Delete the tunnel. */
"deleteTunnel" | 
/**  Check the route works. */
"verify";

/**  The state of one step while applying. */
export type StepState = 
/**  In progress. */
{ state: "running" } | 
/**  Finished. */
{ state: "done" } | 
/**  Not run by the executor (verification happens afterwards). */
{ state: "skipped" } | 
/**  Failed with a message. */
{ state: "failed"; 
/**  What went wrong. */
message: string } | 
/**  Being undone after a later step failed. */
{ state: "undoing" } | 
/**  Undone. */
{ state: "undone" } | 
/**  Couldn't be undone; left in place. */
{ state: "undoFailed"; 
/**  What went wrong. */
message: string };

/**  One step of a plan, as shown in the preview. */
export type StepView = {
	/**  What it does. */
	kind: StepKind,
	/**  One line for the user. */
	description: string,
	/**  "Copy as command" text, when there's an equivalent command. */
	command: string | null,
};

/**  Appearance override. */
export type Theme = 
/**  Follow the system appearance. */
"system" | 
/**  Always light. */
"light" | 
/**  Always dark. */
"dark";

/**  Traffic of one tunnel's connector on this Mac. */
export type Traffic = {
	/**  The last hour, oldest first. */
	points: TrafficPoint[],
	/**  Requests since the connector started. */
	totalRequests: number,
	/**  Failed requests since the connector started. */
	totalErrors: number,
	/**  Edge connections now. */
	connections: number,
	/**  Round-trip time to the edge, in milliseconds. */
	rttMs: number | null,
	/**  Edge locations, e.g. `AMS`. */
	locations: string[],
};

/**  One sample interval. */
export type TrafficPoint = {
	/**  Milliseconds since the epoch. */
	at: number | null,
	/**  Requests during the interval. */
	requests: number,
	/**  Failed requests during the interval. */
	errors: number,
};

/**  A tunnel in the account. */
export type TunnelSummary = {
	/**  Tunnel id. */
	id: string,
	/**  Name. */
	name: string,
	/**  Cloudflare's status: `inactive`, `degraded`, `healthy` or `down`. */
	status: string,
	/**  Created (RFC 3339). */
	createdAt: string,
	/**  Routes in its remote configuration (None: configured locally, or unreadable). */
	routes: number | null,
	/**  Edge connections. */
	connections: ConnectionView[],
	/**  This Mac's tunnel (created and run by Teitunnel here). */
	thisMac: boolean,
	/**  Connector state on this Mac, for this Mac's tunnel. */
	connector: ConnectorState | null,
};

/**  This Mac's tunnel. */
export type TunnelView = {
	/**  Tunnel id. */
	id: string,
	/**  Name. */
	name: string,
	/**  Connector state on this Mac (`None`: not running). */
	connector: ConnectorState | null,
};

/**  Whether a newer cloudflared is available. */
export type UpdateInfo = {
	/**  Latest published version. */
	latest: string,
	/**  Whether it's newer than the one in use (or none is installed). */
	available: boolean,
};

/**  The result of checking one hostname. */
export type Verification = {
	/**  Hostname. */
	hostname: string,
	/**  The origin's HTTP status, when it answered. */
	status: number | null,
	/**  What's wrong, if anything. */
	failure: Failure | null,
	/**  The failure, in a sentence for the UI. */
	message: string | null,
};

/**  Something the user should know before applying. */
export type Warning = 
/**  A record Teitunnel didn't create will be replaced. */
{ type: "replacesForeignRecord"; 
/**  Hostname. */
hostname: string; 
/**  Existing type. */
kind: string; 
/**  Existing content. */
content: string } | 
/**  A record Teitunnel didn't create will be deleted. */
{ type: "deletesForeignRecord"; 
/**  Hostname. */
hostname: string; 
/**  Type. */
kind: string; 
/**  Content. */
content: string } | 
/**  A record Teitunnel didn't create is left in place. */
{ type: "keepsForeignRecord"; 
/**  Hostname. */
hostname: string } | 
/**  No routes are left on the tunnel. */
{ type: "tunnelEmpty" } | 
/**  The origin isn't on this Mac, so it must be reachable from here. */
{ type: "remoteOrigin"; 
/**  The origin. */
origin: string };

/**  DNS permission for one domain. */
export type ZoneGrant = {
	/**  Zone id. */
	zoneId: string,
	/**  Domain name. */
	zoneName: string,
	/**  Whether DNS records can be edited. */
	dnsEdit: Grant,
};

/**  A zone the account can use. */
export type ZoneRef = {
	/**  Zone id. */
	id: string,
	/**  Apex name. */
	name: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

