import { type SpringName, springs, springToCss } from "./motion-tokens.ts";

/** Renders `styles/motion.css`. Kept separate so a test can check the file is current. */
export function renderMotionCss(): string {
  const lines = [
    "/* Generated by scripts/gen-motion-css.ts from src/lib/motion-tokens.ts. Do not edit. */",
    ":root {",
  ];
  for (const name of Object.keys(springs) as SpringName[]) {
    const { easing, durationMs } = springToCss(springs[name]);
    lines.push(`  --ease-${name}: ${easing};`);
    lines.push(`  --duration-${name}: ${durationMs}ms;`);
  }
  lines.push("}", "");
  lines.push(
    "/* Reduce motion: springs become short cross-fades (DESIGN §7). */",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
  );
  for (const name of Object.keys(springs)) {
    lines.push(`    --ease-${name}: linear;`, `    --duration-${name}: 80ms;`);
  }
  lines.push("  }", "}", "");
  return lines.join("\n");
}
