/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MainRouteImport } from "./routes/_main"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as MainIndexRouteImport } from "./routes/_main/index"
import { Route as MainActivityRouteImport } from "./routes/_main/activity"
import { Route as MainAnalyticsRouteImport } from "./routes/_main/analytics"
import { Route as MainCommentsRouteImport } from "./routes/_main/comments"
import { Route as MainDoctorRouteImport } from "./routes/_main/doctor"
import { Route as MainDomainsRouteImport } from "./routes/_main/domains"
import { Route as MainProjectsRouteImport } from "./routes/_main/projects"
import { Route as MainQuickShareRouteImport } from "./routes/_main/quick-share"
import { Route as MainRoutesRouteImport } from "./routes/_main/routes"
import { Route as MainSnapshotsRouteImport } from "./routes/_main/snapshots"
import { Route as MainTunnelsRouteImport } from "./routes/_main/tunnels"
import { Route as MainDevGalleryRouteImport } from "./routes/_main/dev.gallery"
import { Route as MainDevStressRouteImport } from "./routes/_main/dev.stress"

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainRoute,
} as any)
const MainActivityRoute = MainActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => MainRoute,
} as any)
const MainAnalyticsRoute = MainAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => MainRoute,
} as any)
const MainCommentsRoute = MainCommentsRouteImport.update({
  id: "/comments",
  path: "/comments",
  getParentRoute: () => MainRoute,
} as any)
const MainDoctorRoute = MainDoctorRouteImport.update({
  id: "/doctor",
  path: "/doctor",
  getParentRoute: () => MainRoute,
} as any)
const MainDomainsRoute = MainDomainsRouteImport.update({
  id: "/domains",
  path: "/domains",
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => MainRoute,
} as any)
const MainQuickShareRoute = MainQuickShareRouteImport.update({
  id: "/quick-share",
  path: "/quick-share",
  getParentRoute: () => MainRoute,
} as any)
const MainRoutesRoute = MainRoutesRouteImport.update({
  id: "/routes",
  path: "/routes",
  getParentRoute: () => MainRoute,
} as any)
const MainSnapshotsRoute = MainSnapshotsRouteImport.update({
  id: "/snapshots",
  path: "/snapshots",
  getParentRoute: () => MainRoute,
} as any)
const MainTunnelsRoute = MainTunnelsRouteImport.update({
  id: "/tunnels",
  path: "/tunnels",
  getParentRoute: () => MainRoute,
} as any)
const MainDevGalleryRoute = MainDevGalleryRouteImport.update({
  id: "/dev/gallery",
  path: "/dev/gallery",
  getParentRoute: () => MainRoute,
} as any)
const MainDevStressRoute = MainDevStressRouteImport.update({
  id: "/dev/stress",
  path: "/dev/stress",
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof MainIndexRoute
  "/settings": typeof SettingsRoute
  "/activity": typeof MainActivityRoute
  "/analytics": typeof MainAnalyticsRoute
  "/comments": typeof MainCommentsRoute
  "/doctor": typeof MainDoctorRoute
  "/domains": typeof MainDomainsRoute
  "/projects": typeof MainProjectsRoute
  "/quick-share": typeof MainQuickShareRoute
  "/routes": typeof MainRoutesRoute
  "/snapshots": typeof MainSnapshotsRoute
  "/tunnels": typeof MainTunnelsRoute
  "/dev/gallery": typeof MainDevGalleryRoute
  "/dev/stress": typeof MainDevStressRoute
}
export interface FileRoutesByTo {
  "/settings": typeof SettingsRoute
  "/activity": typeof MainActivityRoute
  "/analytics": typeof MainAnalyticsRoute
  "/comments": typeof MainCommentsRoute
  "/doctor": typeof MainDoctorRoute
  "/domains": typeof MainDomainsRoute
  "/projects": typeof MainProjectsRoute
  "/quick-share": typeof MainQuickShareRoute
  "/routes": typeof MainRoutesRoute
  "/snapshots": typeof MainSnapshotsRoute
  "/tunnels": typeof MainTunnelsRoute
  "/": typeof MainIndexRoute
  "/dev/gallery": typeof MainDevGalleryRoute
  "/dev/stress": typeof MainDevStressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_main": typeof MainRouteWithChildren
  "/settings": typeof SettingsRoute
  "/_main/activity": typeof MainActivityRoute
  "/_main/analytics": typeof MainAnalyticsRoute
  "/_main/comments": typeof MainCommentsRoute
  "/_main/doctor": typeof MainDoctorRoute
  "/_main/domains": typeof MainDomainsRoute
  "/_main/projects": typeof MainProjectsRoute
  "/_main/quick-share": typeof MainQuickShareRoute
  "/_main/routes": typeof MainRoutesRoute
  "/_main/snapshots": typeof MainSnapshotsRoute
  "/_main/tunnels": typeof MainTunnelsRoute
  "/_main/": typeof MainIndexRoute
  "/_main/dev/gallery": typeof MainDevGalleryRoute
  "/_main/dev/stress": typeof MainDevStressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/activity"
    | "/analytics"
    | "/comments"
    | "/doctor"
    | "/domains"
    | "/projects"
    | "/quick-share"
    | "/routes"
    | "/snapshots"
    | "/tunnels"
    | "/dev/gallery"
    | "/dev/stress"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/settings"
    | "/activity"
    | "/analytics"
    | "/comments"
    | "/doctor"
    | "/domains"
    | "/projects"
    | "/quick-share"
    | "/routes"
    | "/snapshots"
    | "/tunnels"
    | "/"
    | "/dev/gallery"
    | "/dev/stress"
  id:
    | "__root__"
    | "/_main"
    | "/settings"
    | "/_main/activity"
    | "/_main/analytics"
    | "/_main/comments"
    | "/_main/doctor"
    | "/_main/domains"
    | "/_main/projects"
    | "/_main/quick-share"
    | "/_main/routes"
    | "/_main/snapshots"
    | "/_main/tunnels"
    | "/_main/"
    | "/_main/dev/gallery"
    | "/_main/dev/stress"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_main/": {
      id: "/_main/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/activity": {
      id: "/_main/activity"
      path: "/activity"
      fullPath: "/activity"
      preLoaderRoute: typeof MainActivityRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/analytics": {
      id: "/_main/analytics"
      path: "/analytics"
      fullPath: "/analytics"
      preLoaderRoute: typeof MainAnalyticsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/comments": {
      id: "/_main/comments"
      path: "/comments"
      fullPath: "/comments"
      preLoaderRoute: typeof MainCommentsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/doctor": {
      id: "/_main/doctor"
      path: "/doctor"
      fullPath: "/doctor"
      preLoaderRoute: typeof MainDoctorRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/domains": {
      id: "/_main/domains"
      path: "/domains"
      fullPath: "/domains"
      preLoaderRoute: typeof MainDomainsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/projects": {
      id: "/_main/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/quick-share": {
      id: "/_main/quick-share"
      path: "/quick-share"
      fullPath: "/quick-share"
      preLoaderRoute: typeof MainQuickShareRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/routes": {
      id: "/_main/routes"
      path: "/routes"
      fullPath: "/routes"
      preLoaderRoute: typeof MainRoutesRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/snapshots": {
      id: "/_main/snapshots"
      path: "/snapshots"
      fullPath: "/snapshots"
      preLoaderRoute: typeof MainSnapshotsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/tunnels": {
      id: "/_main/tunnels"
      path: "/tunnels"
      fullPath: "/tunnels"
      preLoaderRoute: typeof MainTunnelsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/dev/gallery": {
      id: "/_main/dev/gallery"
      path: "/dev/gallery"
      fullPath: "/dev/gallery"
      preLoaderRoute: typeof MainDevGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/dev/stress": {
      id: "/_main/dev/stress"
      path: "/dev/stress"
      fullPath: "/dev/stress"
      preLoaderRoute: typeof MainDevStressRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainActivityRoute: typeof MainActivityRoute
  MainAnalyticsRoute: typeof MainAnalyticsRoute
  MainCommentsRoute: typeof MainCommentsRoute
  MainDoctorRoute: typeof MainDoctorRoute
  MainDomainsRoute: typeof MainDomainsRoute
  MainProjectsRoute: typeof MainProjectsRoute
  MainQuickShareRoute: typeof MainQuickShareRoute
  MainRoutesRoute: typeof MainRoutesRoute
  MainSnapshotsRoute: typeof MainSnapshotsRoute
  MainTunnelsRoute: typeof MainTunnelsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainDevGalleryRoute: typeof MainDevGalleryRoute
  MainDevStressRoute: typeof MainDevStressRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainActivityRoute: MainActivityRoute,
  MainAnalyticsRoute: MainAnalyticsRoute,
  MainCommentsRoute: MainCommentsRoute,
  MainDoctorRoute: MainDoctorRoute,
  MainDomainsRoute: MainDomainsRoute,
  MainProjectsRoute: MainProjectsRoute,
  MainQuickShareRoute: MainQuickShareRoute,
  MainRoutesRoute: MainRoutesRoute,
  MainSnapshotsRoute: MainSnapshotsRoute,
  MainTunnelsRoute: MainTunnelsRoute,
  MainIndexRoute: MainIndexRoute,
  MainDevGalleryRoute: MainDevGalleryRoute,
  MainDevStressRoute: MainDevStressRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
